### ISSUE TITLE
drop repack.log table by error

### ISSUE THREAD

**Issue by epa64** [reorg/pg_repack#100]
Hi,
i used repack 1.3.1.
I dropped a bigest table repack.log by error and not the associated repack.table.
I am now a sql insert error.
What can i do?
If i drop and create the repack extension anb start full repack, what append ?
I need help because is production cluster.

Best' regard's
Eric Papet

**Comment by epa64** [comment]
maybe just drop the associated repack.table_xx  ?

**Comment by dvarrazzo** [comment]
You can drop the entire extension and start from scratch.

**Comment by schmiddy** [comment]
Yeah, easiest way is just `DROP EXTENSION pg_repack CASCADE;`. You can also drop individual items by hand if you want to control the process: first drop the trigger on the table, then the repack.table_xxx, and so on.

**Comment by epa64** [comment]
thank's a lot for your time.
I go ...

**Comment by epa64** [comment]
How can find the triger associate white my repack.table ?

**Comment by epa64** [comment]
Ok  select tgrelid,tgname from pg_trigger where tgname like '%repack%';
and tgrelid is the number associate with the table .

**Comment by schmiddy** [comment]
FYI pg_repack's trigger should always be named "z_repack_trigger". If it's still on your table, you can do `DROP TRIGGER z_repack_trigger ON your_table_name;`

**Comment by epa64** [comment]
Hi,
I drop trigger and next table.
```
But this errorINI re_pack (  7/147)                        available_night_period :       483737600
Dec  2 02:50:29 db pop_reindex.py: KO! 254  could not change directory to "/root"#012NOTICE: Setting up workers.conns#012INFO: repacking table "available_night_period"#012WARNING: canceling conflicted backends#012WARNING: canceling conflicted backends#012WARNING: terminating conflicted backends#012ERROR: query failed: ERROR:  type "pk_1704237" already exists#012DETAIL: query was: CREATE TYPE repack.pk_1704237 AS (id bigint).
```
And then table are not reorg by repack and not new  trriger are crete on my table.
In your schema can i delete the pk_1704237 ?

Thank's for your time

regard's
Eric Papet

**Comment by schmiddy** [comment]
Yes, you should be able to `DROP TYPE repack.pk_1704237;`. You can clean out anything else from the repack schema if you get more errors about `repack.*` objects still hanging around.

**Comment by epa64** [comment]
thank's
