### ISSUE TITLE
Installation schema issues

### ISSUE THREAD

**Issue by keithf4** [reorg/pg_repack#105]
Trying to force the schema that pg_repack will install to seems to create some weird issues.

If you try to install the extension to your specific schema without that schema first defined you get this
```
keith@mydb=# create extension pg_repack schema repack;
ERROR:  schema "repack" does not exist
Time: 0.579 ms
```
This is because the check for that schema's existence is done before pg_repack tries to create it in the extension SQL file.

If you pre-define your schema, then explicitly try to install it to that schema, it fails when the SQL file is run because the SQL file tried to define it
```
keith@mydb=# create schema repack;
CREATE SCHEMA
Time: 3.941 ms
keith@mydb=# create extension pg_repack schema repack;
ERROR:  schema "repack" already exists
Time: 2.419 ms
```
Even if you leave the SCHEMA clause off, this still fails
```
keith@mydb=# create extension pg_repack;
ERROR:  schema "repack" already exists
Time: 2.741 ms
```
If you try to install it to a different schema other than the one you have defined, it doesn't actually get installed there, although running `\dx` shows the catalogs think it is.
```
keith@mydb=# create schema testing;
CREATE SCHEMA
Time: 3.530 ms
keith@mydb=# create extension pg_repack schema testing;
CREATE EXTENSION
Time: 39.284 ms
keith@mydb=# \dx
                                         List of installed extensions
      Name      | Version |    Schema     |                            Description                             
----------------+---------+---------------+--------------------------------------------------------------------
 pg_repack      | 1.3.2   | testing       | Reorganize tables in PostgreSQL databases with minimal locks
(12 rows)

keith@mydb=# \dx+ pg_repack 
                       Objects in extension "pg_repack"
                              Object Description                               
-------------------------------------------------------------------------------
 function repack.array_accum(anyelement)
 function repack.conflicted_triggers(oid)
 function repack.disable_autovacuum(regclass)
 function repack.get_assign(oid,text)
 function repack.get_columns_for_create_as(oid)
 function repack.get_compare_pkey(oid,text)
 function repack.get_create_index_type(oid,name)
 function repack.get_create_trigger(oid,oid)
 function repack.get_drop_columns(oid,text)
 function repack.get_enable_trigger(oid)
 function repack.get_index_columns(oid,text)
 function repack.get_order_by(oid,oid)
 function repack.oid2text(oid)
 function repack.repack_apply(cstring,cstring,cstring,cstring,cstring,integer)
 function repack.repack_drop(oid,integer)
 function repack.repack_index_swap(oid)
 function repack.repack_indexdef(oid,oid,name,boolean)
 function repack.repack_swap(oid)
 function repack.repack_trigger()
 function repack.version_sql()
 function repack.version()
 schema repack
 view repack.primary_keys
 view repack.tables
(24 rows)
```
If you don't precreate the schema, and don't give the SCHEMA clause, it seems to install fine
```
keith@mydb=# drop schema repack;
DROP SCHEMA
Time: 3.088 ms
keith@mydb=# create extension pg_repack;
CREATE EXTENSION
Time: 46.512 ms
```
However, if you happened to have a schema defined for your own username (as we do in many of our systems to give people a place to create their own objects), the internal catalogs now think the extension installed in your own schema due to the default search path. However, it's still installed to the `repack` schema above as happened with `testing`
```
keith@mydb=# drop schema repack;
DROP SCHEMA
Time: 3.088 ms
keith@mydb=# create extension pg_repack;
CREATE EXTENSION
Time: 46.512 ms
keith@mydb=# show search_path;
   search_path   
-----------------
 "$user", public
(1 row)

Time: 0.519 ms
keith@mydb=# \dx
                                         List of installed extensions
      Name      | Version |    Schema     |                            Description                             
----------------+---------+---------------+--------------------------------------------------------------------
 pg_repack      | 1.3.2   | keith         | Reorganize tables in PostgreSQL databases with minimal locks
```

Not sure why you are forcing the extension to go into its own predefined schema. Doesn't seem to be a need for it for pg_repack, Plus, you already have `relocatable = false` set in the .control file, so it cannot be changed after installation and cause any issues. In your code, you can use the `@extschema@` macro, and it will automatically replace it with whatever schema the user installed the extension to upon installation.

Recommendation would be to just let the users install it to whichever schema they wish. Can show an example in the readme of creating the `repack` schema and installing it there and most people will probably follow that. That's been my experience with pg_partman so far.

**Comment by dvarrazzo** [comment]
The schema name is referenced in the C code, so `@extschema@` cannot be used. No repack object is really long-lived, so there isn't really an organization need to choose your own name.

**Comment by keithf4** [comment]
You can very easily look up the schema that the extension is installed to within the C code.

https://github.com/keithf4/pg_partman/blob/master/src/pg_partman_bgw.c#L417
