### ISSUE TITLE
Compile warning with PostgreSQL 9.6

### ISSUE THREAD

**Issue by MasahikoSawada** [reorg/pg_repack#109]
Because commit 23a27b039d94ba359286694831eafe03cd970eef changed the type of SPI_processed from `uint32` to `uint64`, we get the compile warning with PostgreSQL 9.6.

```
repack.c: In function 'repack_index_swap':
repack.c:1309: warning: format '%d' expects type 'int', but argument 4 has type 'uint64'
```

Corresponding code is,

```
    if (SPI_processed != 1)
        elog(ERROR, "Could not find index 'index_%u', found %d matches",
             orig_idx_oid, SPI_processed);
```

I thought that we can divide that code using `PG_VERSION_NUM` but it seems to me over kill. One another solution is to put cast to uint64 and change the format identifier from `%d` to `%lu` and backpatch to other supported versions.

Thought?

**Comment by schmiddy** [comment]
I'd support casting to uint64 for all versions in our code, and changing `%d` to ` %lu`.

**Comment by MasahikoSawada** [comment]
Thank you for reply.
Created PR #110 , please view it.
