### ISSUE TITLE
master fails building with PG < 9.5

### ISSUE THREAD

**Issue by dvarrazzo** [reorg/pg_repack#119]
I've set up automated tests with travis. While they pass ok with PG 9.6 and 9.5 building fails with previous versions, see https://travis-ci.org/reorg/pg_repack/builds/215118725

It's possibly something trivial but now I'm tired to investigate. If someone can take a look great, otherwise I'll do when I can.

**Comment by MasahikoSawada** [comment]
I guess issue #63 is related to this.

**Comment by dvarrazzo** [comment]
Yes, that was it. Tests pass now on travis PG 9.2-9.6 \o/
