### ISSUE TITLE
CLI option for MIN_TUPLES_BEFORE_SWITCH

### ISSUE THREAD

**Issue by jwilm** [reorg/pg_repack#126]
I've been running into an issue recently where pg_repack gets stuck replaying the log before swapping tables. Our query volume on that table seems to be high enough that the hardcoded value of `MIN_TUPLES_BEFORE_SWITCH 20` is not enough.

It seems to me that the trade-off with a higher minimum value is a longer time spent holding the access exclusive lock during swap. Is there anything else I'm not thinking of?

I'd like to propose adding a CLI option for specifying that value. Doing so would allow even the busiest tables to be swapped, and the trade-off with lock time is entirely in the hands of the user.

If there is interest here, I'd be happy to put together a patch.

P.S. Thanks for continuing to support this incredibly useful tool. :smile:

**Comment by MasahikoSawada** [comment]
Seems good idea. As you said, it's difficult to determine the timing to switch repacked table under the high throughput circumstances.

**Comment by schmiddy** [comment]
So, I remember running into this issue on a busy production server in the past too -- back in the old days the limit was actually **0**, hence introducing `MIN_TUPLES_BEFORE_SWITCH` in ef4dc5a1fbb25eedd8991fbbfaf4b70e8d33b5cd, and that seemed to help (me) a lot.

My main concern with having this be controllable via a CLI knob is that it can be difficult or impossible to know you'll need to use the knob, or what the right value should be, a priori. I expect that you will only find out after several hours that `pg_repack` has gotten bogged down and you need to be more aggressive about coaxing it into taking an exclusive lock, at which point it's not ideal to kill the whole thing and restart over with some larger (how large?) `--min-tuples-before-switch` option.

Maybe we could figure out some good-enough heuristic to detect that we're getting down towards the end of the repack log table, but we aren't making fast-enough progress to get all the way down to empty, and we should just grab the exclusive lock at that point.

**Comment by jwilm** [comment]
The heuristical approach seems difficult to get right and could potentially add unnecessary complexity. The switch is straight-forward to implement, and it let's users pick precisely how much blocking time for the swap they are willing to deal with (something pg_repack wouldn't have a concept of without measuring replay velocity).

Somewhat tangential to this request, but it looks like, in the case where an exclusive lock cannot be obtained, the replay log would grow quite large while waiting for the lock.

**Comment by andreasscherbaum** [comment]
Handled in this PR: https://github.com/reorg/pg_repack/pull/347
