### ISSUE TITLE
ERROR:  DROP INDEX CONCURRENTLY cannot run inside a transaction block

### ISSUE THREAD

**Issue by dvarrazzo** [reorg/pg_repack#129]
Reported by Justin Pryzby on Reorg-general mailing list

I just found ine one of my logfiles:

Sat May 13 01:23:45 ChST 2017: alarms: alarms_alarm_time_idx(repack non-partitioned)...
WARNING: timed out, do not cancel conflicting backends
WARNING: lock_exclusive() failed in connection for alarms
ERROR: query failed: ERROR:  DROP INDEX CONCURRENTLY cannot run inside a transaction block

I have a few things to fix on our side, but it appears there's an repack bug.
Notably, I just upgraded to pg_repack95-1.4.0.  Let me know if I can provide
more info to diagnose.

Thanks,
Justin

**Comment by justinpryzby** [comment]
called as: /usr/pgsql-9.5/bin/pg_repack -E warning --no-kill-backend -d ts -i ...

**Comment by MasahikoSawada** [comment]
This issue should be fixed by #143, and it's merged.
