### ISSUE TITLE
common/fe_memutils.h: No such file or directory

### ISSUE THREAD

**Issue by coffeebite** [reorg/pg_repack#13]
I am trying to build pg_repack in ubuntu but get the following error

```
/usr/include/postgresql/postgres_fe.h:27:32: fatal error: common/fe_memutils.h: No such file or directory
```

I am on Ubuntu 13.04 and have the following packages installed:
- postgresql-server-9.2
- postgresql-server-dev-9.2
- postgresql-contrib-9.2
- postgresql-client-9.2
- postgresql-common

**Comment by dvarrazzo** [comment]
I think we have moved forward from that.
