### ISSUE TITLE
Is -E (--encoding) option necessary for initdb? 

### ISSUE THREAD

**Issue by kfuru** [reorg/pg_repack#130]
Hello,
I tested pg_repack regression in CentOS7.
But, one test FAILED in my environment.

To create PostgreSQL database cluster, I did the following.
 initdb --no-locale  (Encoding is SQL_ASCII) 

<pre> 
============== running regression test queries        ==============
 test init-extension           ... ok
 test repack                   ... FAILED
 test tablespace               ... ok
 test issue3                   ... ok
</pre>

Looking at regression.diffs,
It seems that it error with INSERT of test data.

<pre>
 $ cat ./regress/regression.diffs
 *** /var/lib/pgsql/pg_repack-ver_1.4.0.1/regress/expected/repack.out    2017-04-26 01:58:09.000000000 +0900
 --- /var/lib/pgsql/pg_repack-ver_1.4.0.1/regress/results/repack.out     2017-05-23 09:49:00.420905000 +0900
 ***************
 *** 98,103 ****
 --- 98,104 ----
   INSERT INTO tbl_badindex VALUES(2, 10);
   -- insert data that is always stored into the toast table if column type is extended.
   INSERT INTO tbl_with_mod_column_storage SELECT 1, array_to_string(ARRAY(SELECT chr(code) FROM generate_series(33,3000) code), '');
 + ERROR:  requested character too large for encoding: 256
   -- This will fail. Silence the message as it's different across PG versions.
   SET client_min_messages = fatal;
   CREATE UNIQUE INDEX CONCURRENTLY idx_badindex_n ON tbl_badindex (n);
 
 ======================================================================
</pre>

Is it mandatory to specify the character code using the -E/--encoding option (e.g.-E UTF8) in this test?

Regards,
kfuru

**Comment by MasahikoSawada** [comment]
As commented in the test, we here need a long string value which is stored into a toast table. Should we change the regression test so that it generates a long random string using only characters that are valid in SQL-ASCII encording? Or should we leave and mention this as a restriction in the docs?

**Comment by dvarrazzo** [comment]
Do we only care about the string being long enough? If so we can limit to just printable ascii and avoid any encoding problem. What about:

    SELECT 1, array_to_string(ARRAY(SELECT chr(code % (127 - 32) + 32)
    FROM generate_series(1,3000) code), '')

**Comment by dvarrazzo** [comment]
Fixing this

**Comment by MasahikoSawada** [comment]
I think the long string must not be fit in BLOCK_SIZE/4 even after compressed. A random long string would be better.

For example, 
`select array_to_string(ARRAY(select md5(code::text) from generate_series(1,100)code) , '');`

**Comment by dvarrazzo** [comment]
Yes I see... I've noticed you are the author of the original test and solution of the problem. I guess you know better how to test the problem. :) I've deleted my branch.

**Comment by MasahikoSawada** [comment]
Okay, I will address this.

The test requires a long string value that is always pushed out to the toast table even after compressed. Currently we generate the fixed string (long enough for 8kb block size) but we would need to do the same thing by generating a random string. I'm concerned that in order to ensure the long string value is pushed out to the toast table we might need to have a long random string data in pg_repack repository (at least BLOCK_SIZE/4 bytes). Or we can generate such a string during the regression test, the string might not be pushed out though.

**Comment by dvarrazzo** [comment]
We can just generate a much longer string, 100x8k, out of random numbers using `setseed()` to make it repeatable?

```
piro=# select setseed(0);
piro=# select array_to_string(ARRAY(SELECT chr((random() * (127 - 32) + 32)::int) FROM generate_series(1,40) code), '');
pEjlw3@i:UM\CQzw\d-Z"7-l/F,*5QpZ<]RO|<i
piro=# select setseed(0);
piro=# select array_to_string(ARRAY(SELECT chr((random() * (127 - 32) + 32)::int) FROM generate_series(1,40) code), '');
pEjlw3@i:UM\CQzw\d-Z"7-l/F,*5QpZ<]RO|<i
```

Sure it is not very compressible:

```
psql -tXA  -c  "select setseed(0); select array_to_string(ARRAY(SELECT chr((random() * (127 - 32) + 32)::int) FROM generate_series(1,1024 * 1024) code), '');"  | bzip2 | wc -c
872234
```

**Comment by MasahikoSawada** [comment]
The using setseed() looks perfect. Thank you for the advice!
I'll make a PR.

**Comment by MasahikoSawada** [comment]
Created the PR. Since a very long string (>8kB) is stored into toast table even if the storage type is `main` I inserted a 3kB random string.

**Comment by MasahikoSawada** [comment]
Fixed

**Comment by MasahikoSawada** [comment]
Should we add this fix to the docs?

**Comment by dvarrazzo** [comment]
I don't think it is necessary: it is not a change in the program's behaviour, it is just tests.

**Comment by MasahikoSawada** [comment]
Agreed.
