### ISSUE TITLE
error during MAKE of pg_repack

### ISSUE THREAD

**Issue by Gizardpuke** [reorg/pg_repack#137]
im trying to set up pg_repack on a VM i have as a test at work, but i getting the error during the make process. im running on RHEL 6.5 (same as our production environments). im a DBA by trade, and trying to figure this out, but nothing online is providing any information other than, its a library link issue. 

problem is, if thats the case, i dont know where to look. and the other lunix admins here dont know ether, as our PP environments are centos, and not RHEL like production (dont ask).

any help greatly appreciated. 
Mark.

[root@markk5-rhel tmp]# cd pg_repack-1.4.0/
[root@markk5-rhel pg_repack-1.4.0]# ls -ltr
total 40
drwxr-xr-x. 2 root root 4096 Apr 26 04:58 SPECS
drwxr-xr-x. 4 root root 4096 Apr 26 04:58 regress
-rw-r--r--. 1 root root 2201 Apr 26 04:58 README.rst
drwxr-xr-x. 2 root root 4096 Apr 26 04:58 msvc
-rw-r--r--. 1 root root 1285 Apr 26 04:58 META.json
-rw-r--r--. 1 root root 1553 Apr 26 04:58 Makefile
drwxr-xr-x. 3 root root 4096 Apr 26 04:58 lib
drwxr-xr-x. 2 root root 4096 Apr 26 04:58 doc
-rw-r--r--. 1 root root 1662 Apr 26 04:58 COPYRIGHT
drwxr-xr-x. 3 root root 4096 Apr 26 04:58 bin
[root@markk5-rhel pg_repack-1.4.0]# make
make[1]: Entering directory `/tmp/pg_repack-1.4.0/bin'
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -I/usr/include/et -I/usr/pgsql-9.4/include -DREPACK_VERSION=1.4.0 -I. -I./ -I/usr/pgsql-9.4/include/server -I/usr/pgsql-9.4/include/internal -I/usr/include/et -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o pg_repack.o pg_repack.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -I/usr/include/et -I/usr/pgsql-9.4/include -DREPACK_VERSION=1.4.0 -I. -I./ -I/usr/pgsql-9.4/include/server -I/usr/pgsql-9.4/include/internal -I/usr/include/et -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o pgut/pgut.o pgut/pgut.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -I/usr/include/et -I/usr/pgsql-9.4/include -DREPACK_VERSION=1.4.0 -I. -I./ -I/usr/pgsql-9.4/include/server -I/usr/pgsql-9.4/include/internal -I/usr/include/et -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o pgut/pgut-fe.o pgut/pgut-fe.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -I/usr/include/et pg_repack.o pgut/pgut.o pgut/pgut-fe.o -L/usr/pgsql-9.4/lib -lpq -L/usr/pgsql-9.4/lib -L/usr/lib64 -Wl,--as-needed  -lpgcommon -lpgport -lssl -lcrypto -lz -lreadline -lrt -lcrypt -ldl -lm -o pg_repack
/usr/bin/ld: cannot find -lssl
collect2: ld returned 1 exit status
make[1]: *** [pg_repack] Error 1
make[1]: Leaving directory `/tmp/pg_repack-1.4.0/bin'
make: *** [all] Error 2

**Comment by MasahikoSawada** [comment]
I guess you need to install `openssl-devel` package.

**Comment by dvarrazzo** [comment]
I guess so
