### ISSUE TITLE
pg_repack not "organizing" table.

### ISSUE THREAD

**Issue by acmzero** [reorg/pg_repack#138]
I'm trying to organize a table based on a timestamp column, I executed -o "start_time" and I see everything finishes successfully but the rows inside the pages are not ordered at all.

After digging deeper I found that when copying the rows from the original table to the temporal table there is no `ORDER BY` clause, leaving the table in the same order as the original.

I manage to order the table by modifying the copy_data column at view repack.tables  by appending 
`|| (case when repack.oid2text(r.oid)='target_table' then ' order by start_time' else '' end)` 

You can find more details here:
[pg_repack not organizing table](https://dba.stackexchange.com/questions/182315/pg-repack-not-organizing-table-by-column)

**Comment by MasahikoSawada** [comment]
Thank you for reporting.

I could reproduce this issue, and it seems to me that it's a bug of pg_repack. commit 5adff6ff0b88d6f162719eff7176069730537c2a added this bug. We should have add `ORDER BY` to the copy SQL. I'll fix it on this weekend.

**Comment by dvarrazzo** [comment]
Fixed in pg_repack 1.4.1, just released.

**Comment by acmzero** [comment]
I can confirm this is fixed.

Awesome!!!

Thanks.
