### ISSUE TITLE
Upgrade issue from pg_repack 1.4.0 + pg9.6 to pg10 and pg_repack 1.4.2

### ISSUE THREAD

**Issue by xarg** [reorg/pg_repack#155]
After upgrading to postgres 10 and pg_repack 1.4.2 I get this error when trying to repack a table:

```
/usr/lib/postgresql/10/bin/pg_repack -d db -t table
ERROR: pg_repack failed with error: extension 'pg_repack 1.4.2' required, found extension 'pg_repack 1.4.0'
```

But I have the 1.4.2 installed:

```
psql (10.0)
Type "help" for help.

postgres=# \dx
                                  List of installed extensions
   Name    | Version |   Schema   |                         Description
-----------+---------+------------+--------------------------------------------------------------
 pg_repack | 1.4.2   | public     | Reorganize tables in PostgreSQL databases with minimal locks
```

I tried dropping and creating it again, but got the same error.

**Comment by keithf4** [comment]
Your pg_repack command is connecting to the "db" database, but your psql prompt shows you're logged into the "postgres" database. Extensions are installed on a per-database basis, not cluster-wide.

**Comment by xarg** [comment]
@keithf4 That was it! Thanks a lot! 

I dropped the extension from the database and then created it again and it worked.
