### ISSUE TITLE
pg_repack doesn't run: No workers to disconnect message

### ISSUE THREAD

**Issue by Shazzaam** [reorg/pg_repack#156]
This was working last week but now all I get is this "No workers to disconnect" message. I upgraded from 1.4.1 to 1.4.2 and it didn't make a difference. This table is about 70 GB with indexes and has writes throughout the day.

-bash-4.2$ pg_repack -o "user_id,start_gmt_time" -t tbl_user_config -E DEBUG -e
DEBUG: No workers to disconnect.
LOG: (query) select repack.version(), repack.version_sql()
LOG: (query) SET statement_timeout = 0
LOG: (query) SET search_path = pg_catalog, pg_temp, public
LOG: (query) SET client_min_messages = warning
LOG: (query) SELECT t.*, coalesce(v.tablespace, t.tablespace_orig) as tablespace_dest FROM repack.tables t,  (VALUES (quote_ident($1::text))) as v (tablespace) WHERE (relid = $2::regclass) ORDER BY t.relname, t.schemaname
LOG: 	(param:0) = (null)
LOG: 	(param:1) = tbl_user_config
DEBUG: No workers to disconnect.

**Comment by schmiddy** [comment]
I think the "No workers to disconnect" DEBUG messages are benign / a red-herring. It looks like somehow `tbl_user_config` isn't being picked up as eligible to be repacked. We try to print out a message (like "... must have a primary key or not-null unique keys" or "relation ... does not exist") when that happens but maybe we're missing this case somehow. Is there anything unusual about the schema of this table?

**Comment by Shazzaam** [comment]
These are the column types in that table:

<img width="327" alt="screen shot 2017-10-25 at 9 19 03 pm" src="https://user-images.githubusercontent.com/96428/32031979-3aaef932-b9ca-11e7-84c7-d77dc9542965.png">

There is no primary key but there is a not-null unique index on the int8, varchar, timestamp and numeric columns.

I can't think of anything else out of the ordinary with this table.

**Comment by Shazzaam** [comment]
Ok, it looks like it was skipping it because my table was UNLOGGED. Is this intended?

**Comment by schmiddy** [comment]
Ah-hah, yup that would be why. We don't really support UNLOGGED tables (and I'm not sure it would really make sense for us to do so), though we should definitely do a better job of making that clear in the output that the table is being skipped intentionally and not mysteriously. Some more details in #71.
