### ISSUE TITLE
Feature: Support re-typing a column i.e. int to bigint

### ISSUE THREAD

**Issue by jfinzel** [reorg/pg_repack#158]
The ideal type of workflow that would be required to re-type a column from int to bigint (or smallint to int) on a large table I would think would be almost identical to what pg_repack does.  What additionally would be needed would be to change the data type on whatever column(s) want to be re-typed, and also to do sequence changes.

Consider the following example: A table has overrun integer in its sequence.  As a quick fix, we change the sequence to a negative integer now counting through negative numbers.  But what we really need is to re-type both the column and sequence to be a bigint.  Another "nice to have" would be to actually set the sequence during this operation to what we want so that we could actually later fix the negative sequences to be again positive bigint numbers.

Rather than trying to create a separate project for it that mimics most of pg_repack's logic, what are your thoughts on adding a feature to support this operation?

**Comment by dvarrazzo** [comment]
That it is not possible, as well as removing physically dropped columns, reordering column etc. I wish it was.

**Comment by jfinzel** [comment]
It would be possible if you didn't catalog-swap the table, but actually dropped the old table and renamed the repack table to the old table's name in a plain SQL transaction.  Granted, that would also be a big departure from how pg_repack normally swaps the tables.

**Comment by schmiddy** [comment]
I kind of wish we didn't have to do the catalog swapping, but IIRC one reason we need it is to avoid problems with tables having a FK reference to the target table.

**Comment by dvarrazzo** [comment]
@jfinzel pg_repack replaces the physical table under the metadata of the existing table in the catalog (recently I've learned that this is copied from the implementation of the CLUSTER command). Changing the catalog itself is not supported by postgres. It's not like "I don't want".
