### ISSUE TITLE
pg_repack on pg_largeobject table 

### ISSUE THREAD

**Issue by epa64** [reorg/pg_repack#163]
Hi,

Is it possible to perform pg_repack on pg_catalog.pg_largeobject.
The pg_catalog.pg_largeobject have no primary key.
My pg_repack version is 1.4.2 and posgresql is 9.1.
I just perform vacuumlo on pg_large object for delete the orphelin.
Now i want to recover space in my disk.
The size of pg_largeobject is 963 GB and it's production database.
The Vacuum Full is not possible in production because the table is locked.

Thank's for your help
Best regards
Eric PAPET

**Comment by MathCharton** [comment]
UP

**Comment by dvarrazzo** [comment]
No. pg_repack doesn't work on system catalog tables.
