### ISSUE TITLE
autovacuum preventing exclusive lock on table

### ISSUE THREAD

**Issue by MichaelDBA** [reorg/pg_repack#167]
I have specified "-D" so that pg_repack will not try to kill other backends interfering with it, but I didn't expect this to apply to autovacuum doing normal table processing?

Is there some way to prevent other user conflicts as was intended, but not to allow autovacuum to interfere with pg_repack running?

It looks like I have to do a manual ALTER TABLE before and after running pg_repack:
```
ALTER TABLE mytable SET (autovacuum_enabled = false, toast.autovacuum_enabled = false);
pseudocode: do pg_repack on mytable
ALTER TABLE mytable SET (autovacuum_enabled = true, toast.autovacuum_enabled = true);


```

**Comment by MichaelDBA** [comment]
How about this new parameter:
`-O, --overlook-autovacuum     Ignore autovacuum when considering other conflicting backends`

**Comment by jfinzel** [comment]
I am also seeing issues I never saw before with repack.  I never used to see any waiting transactions, because the try for the lock would not actually be waiting continuously, but would try for a lock, and cancel and retry each time.  Now I see a hard lock wait.  What happened?

**Comment by bashtanov** [comment]
@MichaelDBA what version do you use? #87, which is in 1.4.0 and later, looks like a fix for your problem.

**Comment by MichaelDBA** [comment]
This problem occurs with 1.4.2 so it was not something fixed in 1.4.0.  Think this is still a valid bug.

**Comment by MichaelDBA** [comment]
Here is a snippet of stdout when running pg_repack:
```
LOG: (query) BEGIN ISOLATION LEVEL READ COMMITTED
LOG: (query) SET LOCAL statement_timeout = 100
LOG: (query) LOCK TABLE sys_order IN ACCESS EXCLUSIVE MODE
LOG: (query) ROLLBACK
LOG: (query) BEGIN ISOLATION LEVEL READ COMMITTED
LOG: (query) SET LOCAL statement_timeout = 200
LOG: (query) LOCK TABLE sys_order IN ACCESS EXCLUSIVE MODE
LOG: (query) ROLLBACK
LOG: (query) BEGIN ISOLATION LEVEL READ COMMITTED
LOG: (query) SET LOCAL statement_timeout = 300
LOG: (query) LOCK TABLE sys_order IN ACCESS EXCLUSIVE MODE
LOG: (query) ROLLBACK
```
So it is appears to be waiting for an exclusive lock and an autovacuum on this table is running during the  pg_repack operation.

**Comment by MichaelDBA** [comment]
Is there any reason why this issue is not being addressed?  I created it on January 18, 2018.

The only input I got was that they think it was fixed in 1.4 and I immediately responded that I was working with version 1.4.2

**Comment by jwilm** [comment]
@MichaelDBA it's attitudes like that which makes people give up contributing to open source projects. Everyone here is a volunteer, and they don't owe you a response at all if they don't feel like it. Please drop the entitlement.

If this feature is so important to you, perhaps a gentle nudge like

> Hey everyone, friendly ping that I'm still interested in fixing this issue. I'm willing to do the work to implement a resolution, and I am just looking for buy-in on the approach to a fix.

**Comment by MichaelDBA** [comment]
What attitude?  I simply pointed out that I had not received any feedback in this open issue in months?  I didn't use caps, exclamation points, insulting words, etc.  Where do you detect the attitude problem?

**Comment by jwilm** [comment]
@MichaelDBA this isn't an attack on your character; there's no need to be defensive. It's just that OSS maintainers have to deal with a lot of stuff, and entitled-sounding comments just drain away motivation. There's a good chance that, with more positive messaging, you can both get what you want _and_ lift up the maintainers of this project (which will, long term, get you more of what you want).

> Please point out what I said that indicated an attitude problem on my part.

It's about entitlement. Examples:

> Is there any reason why this issue is not being addressed?

comes with a ton of subtle messaging that you feel this is more important than whatever else the maintainers have going on, whether its other tickets in this project, real life obligations, or just not feeling like contributing to OSS. This is very nearly a demand in the form of a question.

> as a production user of pg_repack for years now,

subtext: I've been committed to this project for years and my issues should carry extra weight / are more important

> I have been involved in finding bugs that were addressed and fixed and I think I contribute to the stability of this product by doing so.

subtext: I've contributed back, and in reciprocity, my issues should carry extra weight / are more important

Note that I do appreciate your efforts; my company and I have almost certainly benefited from your debugging work, Thank you!

> There are new competing non blocking solutions out there that are actively addressing issues

subtext: I'm not committed to this project, but I want the project to be committed to me.

Taken as a whole, this messaging is suggestive of why you feel the project should be invested in solving your problem, and you don't see why they haven't prioritized this issue.

Said another way, you feel entitled to an expedited resolution. And like, I get it. You've sent patches. You've been loyal. But at the end of the day, volunteers don't owe anyone anything, no matter who it is. Just, idk, have more empathy for the people doing free work on your behalf.

**Comment by MichaelDBA** [comment]
so here we are many months later and still no progress, very disappointing.

**Comment by dvarrazzo** [comment]
@MichaelDBA you speak like you ever contributed anything to this project, or proposed to do so.

People have obviously other priorities than fixing your bug. I have other 4 projects to juggle, a full-time job, and more urgent and complex bug to fix than this within this project.

Provide a solution and we'll merge it, or stop being a nuisance as others already pointed out you are being.

**Comment by MichaelDBA** [comment]
I will stick with my workaround.  I reviewed above comments on this thread and I just don't get it about how I have been a "nuisance".  I think I'm not the one with the attitude problem.  Consider my issue "resolved".

**Comment by bashtanov** [comment]
Despite all the communication problems, just in case someone looks into the issue: it's very weird, as the string provided by @MichaelDBA in https://github.com/reorg/pg_repack/issues/167#issuecomment-367363040 should be caught by https://github.com/reorg/pg_repack/pull/87/files#diff-63c16c22d5edbb07db748a9843eff2d5R89 . So it sounds like one would have to debug if they face this issue again.

**Comment by zakeryooo** [comment]
Anyone else still having this issue? I'm using 1.5.0 and if I execute `pg_repack` with the `-D` option while an autovacuum is running it fails to get the lock. The second autovacuum finishes it works fine, it's not an issue to me because I only run `pg_repack` once in a while manually but presumably based on the commit above this isn't intended behaviour?

Do you still manually disable `autovacuum_enabled` on the table before a repack @MichaelDBA ?

**Comment by piskvorky** [comment]
I think it's fair to say @MichaelDBA is done with this project, following the gaslighting above :)
