### ISSUE TITLE
No `cluster` shown when `\d+ tablename` after a `pg_repack -o colname`

### ISSUE THREAD

**Issue by bobbyrullo** [reorg/pg_repack#173]
I am not sure if this is expected behavior or not, but I don't know where else to ask.

Steps to reproduce:
1. Create a table
1. call pg_repack on that table with the `-o` option
1. go to psql and describe table with `\d+ tablename`
1. Observe no index has `CLUSTER` attribute

Is it expected to not see the CLUSTER attribute, since `CLUSTER on` wasn't called explicitly?

**Comment by dvarrazzo** [comment]
No, it is not expected.
