### ISSUE TITLE
pg_repack make fails on AWS Linux AMI

### ISSUE THREAD

**Issue by baldpope** [reorg/pg_repack#178]
Attempting to build/install pg_repack on an aws linux ami ec2 instance. the various devel packages are installed, postgresql96-devel, readline-devel, and openssl-devel.  make still complains for pgcommon and pgport:

host# make
make[1]: Entering directory `/root/pg_repack-1.4.2/bin'
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 pg_repack.o pgut/pgut.o pgut/pgut-fe.o -L/usr/lib64/pgsql96 -lpq -L/usr/lib64/pgsql96 -Wl,--as-needed  -lpgcommon -lpgport -lssl -lcrypto -lz -lreadline -lrt -lcrypt -ldl -lm -o pg_repack
/usr/bin/ld: cannot find -lpgcommon
/usr/bin/ld: cannot find -lpgport
collect2: error: ld returned 1 exit status
make[1]: *** [pg_repack] Error 1
make[1]: Leaving directory `/root/pg_repack-1.4.2/bin'
make: *** [all] Error 2

I reviewed these 2 threads, 
https://github.com/reorg/pg_repack/issues/7
https://github.com/reorg/pg_repack/issues/77

However, I'm not clear on how pgcommon and/or pgport were finally referenced.  Could you provide some direction.

**Comment by baldpope** [comment]
Figured it out, there is an additional static library package which is available to install, on Centos (aws linux ami) it's **postgresql96-static-9.6.6**

pg_repack build completes without error now.

**Comment by baldpope** [comment]
For those coming across this in the future, this is what I needed:

- yum install readline-devel openssl-devel postgresql96-static-9.6.6 postgresql96-devel-9.6.6
- unzip pg_repack-1.4.2.zip
- cd pg_repack-1.4.2
- make

Hopefully that helps someone in the future.

**Comment by Fran-Rg** [comment]
For AWS 2023:
```
sudo pip install pgxnclient
sudo yum install -y zlib-devel.x86_64 postgresql15.x86_64 postgresql15-server-devel.x86_64 postgresql15-static.x86_64 readline-devel openssl-devel 
sudo pgxn install pg_repack
pg_repack --version
```
