### ISSUE TITLE
Impact on Replication Slots

### ISSUE THREAD

**Issue by jwg2s** [reorg/pg_repack#186]
Hi,

We use replication slots in postgres for various reasons. We also would like to use pg_repack more in order to minimize bloat in scenarios where out autovacuum settings can't recover from a shock to the system that causes significant bloat.

However, we've noticed that if we use pg_repack, the data that then must flow through the replication slot is enormous for large tables. This can sometimes even cause the database to run out of memory and crash. How would you recommend we mitigate against that? Is it even possible?

The only thing that came to mind was to pause all replication, perform the repacks, and then do a full resync, but that feels very heavy-handed, so I'm hoping there's a more graceful solution.

**Comment by Melkij** [comment]
Hello
pg_repack makes full table copy, swap and finally drop old (original bloated) table. Obviously full new table data with indexes is streamed via replication protocol. This is how postgresql replication works.
pg_repack works this way and it is not possible to reduce amount of replicated data. And pg_repack has no options to slow down process.

You can find useful another tool called [pgcompacttable](https://github.com/dataegret/pgcompacttable) - it was designed for inplace table compact and perform delays between operations to minimize WAL rate. Works slower, but with much less impact for production.

We using both pgcompacttable and pg_repack, one in some cases, the other in others.

**Comment by jwg2s** [comment]
@Melkij very interesting - I will check that tool out as well! One of the reasons we were leaning towards pg_repack was that it is RDS compatible. I'll definitely check out https://github.com/dataegret/pgcompacttable and see if that's compatible as well.

**Comment by jwg2s** [comment]
We ended up just dropping the replication slots, repacking the tables, and then re-adding the replication slots and performing full resyncs if anyone else runs into this issue.

**Comment by 0xtrou** [comment]
@jwg2s what about the replication instance? do we have to do pg_repack on the replication instance too?
