### ISSUE TITLE
User with superuser privileges returns ERROR: pg_repack failed with error: You must be a superuser to use pg_repack

### ISSUE THREAD

**Issue by arossouw** [reorg/pg_repack#190]
When attempting to repack a table get the following error:
ERROR: pg_repack failed with error: You must be a superuser to use pg_repack

Assigned superuser privileges to a user:
```
alter user lottostar_dev with superuser;
```

Then executed following command:
```sh
 /usr/lib/postgresql/9.5/bin/pg_repack -t play_systememail prodtest_restoredb -U lottostar_dev
```

```sh
/usr/lib/postgresql/9.5/bin/pg_repack --version
pg_repack 1.4.3
```
Expected for pg_repack to not produce an error

Postgresql 9.5.12

After running following commands:
```sql
ALTER DEFAULT PRIVILEGES IN SCHEMA repack GRANT INSERT ON TABLES TO PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA repack GRANT USAGE, SELECT ON SEQUENCES TO PUBLIC;
```
 repack is successful

**Comment by chaws** [comment]
Don't know if it's still useful, but passing `-k` to it will skip root-user checks. From [pg_repack docs](https://reorg.github.io/pg_repack/):

> -k, --no-superuser-check
Skip the superuser checks in the client. This setting is useful for using pg_repack on platforms that support running it as non-superusers.
