### ISSUE TITLE
Is it possible to execute pg_repack using SQL?

### ISSUE THREAD

**Issue by gajus** [reorg/pg_repack#196]
As far as I can see, there is no documented way of initiating pg_repack from using SQL produce as opposed to the CLI client.

Is it possible to execute pg_repack using SQL?

**Comment by Melkij** [comment]
Hello
For now is no way to run pg_repack without external control utility.
Some part of pg_repack logic can be in theory implements as pg11+ procedure call, but not all. For example, logic for canceling conflicted backend can not be done without separate connection.

Well, you can call same SQL commands as it does pg_repack control utility. But pg_repack does not guarantee any compatibility of pg_repack extension across different pg_repack releases.

**Comment by gajus** [comment]
Understood. Thank you for the answer.

It would be a nice feature to have though.
