### ISSUE TITLE
Canceled "RESET statement_timeout" due to statement_timeout=100ms

### ISSUE THREAD

**Issue by NikolayS** [reorg/pg_repack#200]
On a busy server we've got this multiple times:

```bash
Jan 10 16:51:33 ERROR: query failed: ERROR:  canceling statement due to statement timeout
Jan 10 16:51:33 DETAIL: query was: RESET statement_timeout
```

I assume that `SET LOCAL statement_timeout = 100ms` exists only for the subsequent `LOCK TABLE ..` command, doesn't it? It is not expected that `RESET` might be so long – but it happened.

If so, isn't it better to use `SET LOCAL lock_timeout ...` instead? `RESET` will not be limited by it, while for `LOCK TABLE ..` the same effect as with setting `statement_timeout` will be achieved.

**Comment by dvarrazzo** [comment]
`SET LOCAL` has effect in a transaction, as opposite as in the whole session as `SET` does. There is no explicit connection to the locks (except that the locks are also released at the end of the transaction).

Apart from this hint, your questions relate the behaviour of the Postgres server, not psycopg. You should make them to the right place, such as the pgsql-general mailing list.

**Comment by dvarrazzo** [comment]
Oops sorry, I thought this issue was opened to the psycopg bug tracker :P re-opening...

**Comment by NikolayS** [comment]
np @dvarrazzo 
let me know if I need to explain the problem in more detailed fashion

**Comment by dvarrazzo** [comment]
I wouldn't know if it work. You can try and let us know. I find it extremely dodgy however that it times out and maybe you should ask postgres developer about why that's the case. What postgres version are you using?

**Comment by NikolayS** [comment]
It was 9.6.11 in my case, but I don't think it's "dodgy" – in a very busy cluster any command can take significant time, so can `SET` or `RESET`. It is still communication with server, so in a busy database it might be long.

From analyzing pg_repack's behavior, I see that `set lock_timeout ...` will be better than `set statement_timeout` in this case: it will limit `LOCK ..`, but not limit `RESET ...`

Maybe `statement_timeout` is being used it's just because `lock_timeout` was added relatively not long ago – in 9.3. And 9.3 and older version are already not supported by community, by the way.

Of no particular reason right to keep `statement_timeout` – let's change it, I can create a PR, with version checks, keeping `statement_timeout` approach for 9.2 and older. This will improve pg_repack's not letting it fail on long-running `RESET`.

**Comment by NikolayS** [comment]
@dvarrazzo 
It was 9.6.11 in my case, but I don't think it's "dodgy" – in a very busy cluster any command can take significant time, so can `SET` or `RESET`. It is still communication with server, so in a busy database it might be long.

From analyzing pg_repack's behavior, I see that `set lock_timeout ...` will be better than `set statement_timeout` in this case: it will limit `LOCK ..`, but not limit `RESET ...`

Maybe `statement_timeout` is being used it's just because `lock_timeout` was added relatively not long ago – in 9.3. And 9.3 and older version are already not supported by community, by the way.

Of no particular reason right to keep `statement_timeout` – let's change it, I can create a PR, with version checks, keeping `statement_timeout` approach for 9.2 and older. This will improve pg_repack's not letting it fail on long-running `RESET`.

**Comment by dvarrazzo** [comment]
@NikolayS yes, I thought the same: probably the use of `statement_timeout` predates the introduction of `lock_timeout`, and afaics `lock_timeout` is supported in all the currently supported PostgreSQL versions, so yeah we could use `statement_timeout` as a fallback but it's an extra courtesy.

**Comment by Zhann** [comment]
Did anyone find a workaround for this? We're hitting this sporadically on some of our clusters.
