### ISSUE TITLE
Clarification on super-user requirements

### ISSUE THREAD

**Issue by bradnicholson** [reorg/pg_repack#201]
The docs are conflicting on the need for running as a superuser.

At the top, the is the following NOTICE 

`Only superusers can use the utility.`

But then lower down, we have the `-k` option which is to allow the utility to run as a non-superuser with the following:

`Skip the superuser checks in the client. This setting is useful for using pg_repack on platforms that support running it as non-superusers.`

Can you clarify superuser requirements please?

**Comment by jdmintz** [comment]
I have the same question. Can you shed any light here, please.

**Comment by dvarrazzo** [comment]
Going by memory:

- you need to be a superuser to install the extension
- you should be a superuser so that you will have no permission problem during the operation
- you can skip the superuser check using `-k` as long as you have all the required permissions on the table to repack. If you don't, some operation may fail down the line

if I'm wrong please correct me.

**Comment by bradnicholson** [comment]
It doesn't appear to be working this way.

I create the extension as the DB super user.  Then I try and run it as an unprivliged user against a table that I own.

First set of failures are permissions issues:

```
pg_repack -k  -U admin -d test  -t foo
ERROR: pg_repack failed with error: ERROR:  permission denied for schema repack
LINE 1: select repack.version(), repack.version_sql()
```

Which is understandable (but contrary to the docs).

We can grant permissions fairly simply to the underlying objects such as:

```
GRANT ALL on SCHEMA repack to admin;
GRANT SELECT ON repack.primary_keys TO admin;
GRANT SELECT ON repack.tables TO admin;
GRANT EXECUTE ON FUNCTION repack.array_accum(anyelement) TO admin;
GRANT EXECUTE ON FUNCTION repack.version() TO admin;
GRANT EXECUTE ON FUNCTION repack.version_sql() TO admin;
GRANT EXECUTE ON FUNCTION repack.oid2text(oid) TO admin;
GRANT EXECUTE ON FUNCTION repack.get_index_columns(oid, text) TO admin;
GRANT EXECUTE ON FUNCTION repack.get_order_by(oid, oid) TO admin;
GRANT EXECUTE ON FUNCTION repack.get_create_index_type(oid, name) TO admin;
GRANT EXECUTE ON FUNCTION repack.get_create_trigger(oid, oid) TO admin;
GRANT EXECUTE ON FUNCTION repack.get_enable_trigger(oid) TO admin;
GRANT EXECUTE ON FUNCTION repack.get_assign(oid, text) TO admin;
GRANT EXECUTE ON FUNCTION repack.get_compare_pkey(oid, text) TO admin;
GRANT EXECUTE ON FUNCTION repack.get_columns_for_create_as(oid) TO admin;
GRANT EXECUTE ON FUNCTION repack.get_drop_columns(oid, text) TO admin;
GRANT EXECUTE ON FUNCTION repack.get_storage_param(oid) TO admin;
GRANT EXECUTE ON FUNCTION repack.get_alter_col_storage(oid) TO admin;
GRANT EXECUTE ON FUNCTION repack.repack_indexdef(oid, oid, name, boolean) TO admin;
GRANT EXECUTE ON FUNCTION repack.repack_trigger() TO admin;
GRANT EXECUTE ON FUNCTION repack.conflicted_triggers(oid) TO admin;
GRANT EXECUTE ON FUNCTION repack.disable_autovacuum(regclass) TO admin;
GRANT EXECUTE ON FUNCTION repack.repack_apply(cstring, cstring, cstring, cstring, cstring, integer) TO admin;
GRANT EXECUTE ON FUNCTION repack.repack_swap(oid) TO admin;
GRANT EXECUTE ON FUNCTION repack.repack_drop(oid, integer) TO admin;
GRANT EXECUTE ON FUNCTION repack.repack_index_swap(oid) TO admin;
GRANT EXECUTE ON FUNCTION repack.get_table_and_inheritors(regclass) TO admin;
```

And pg_repack goes fails looping on this:

```
pg_repack -k  -U admin -d test  -t foo
INFO: repacking table "public.foo"
ERROR: query failed: ERROR:  must be superuser to use repack_apply function
DETAIL: query was: SELECT repack.repack_apply($1, $2, $3, $4, $5, $6)
ERROR: query failed: ERROR:  must be superuser to use repack_drop function
DETAIL: query was: SELECT repack.repack_drop($1, $2)
```

**Comment by bradnicholson** [comment]
I see what is happening.  This functionality is broken.  This 

https://github.com/reorg/pg_repack/blob/master/lib/repack.c#L111

Is not defined in pg_repack - so I presume it is coming in from PG.  This is always going to evaluate to the actual superuser status - which ignores the `-k` flag.

I'll file a new issue since this one was really just an inquiry.
