### ISSUE TITLE
warning redirecting incorrect #include <sys/poll.h> to <poll.h>

### ISSUE THREAD

**Issue by ereli-cb** [reorg/pg_repack#203]
See
https://github.com/reorg/pg_repack/blob/923fa2f3c709a506e111cc963034bf2fd127aa00/bin/pg_repack.c#L38

```1gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -I/usr/local/include -DREPACK_VERSION=1.4.4 -I. -I./ -I/usr/local/include/postgresql/server -I/usr/local/include/postgresql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o pg_repack.o pg_repack.c
In file included from pg_repack.c:38:0:
/usr/include/sys/poll.h:1:2: warning: #warning redirecting incorrect #include <sys/poll.h> to <poll.h> [-Wcpp]
 #warning redirecting incorrect #include <sys/poll.h> to <poll.h>
```

If you change it from `sys/poll.h`to `poll.h` it works.

**Comment by MasahikoSawada** [comment]
Thank you for reporting!

Hmm, POSIX recommends including `poll.h`, not `sys/poll.h` but we would fail to compile with older glibc?

**Comment by ereli-cb** [comment]
I don't know why this happens. I was trying to build pg_repack on AWS linux (`Amazon Linux AMI release 2018.03`)

**Comment by ereli-cb** [comment]
I wasn't able to reproduce the issue when using this Docker image https://github.com/ereli-cb/pg_repack/blob/master/test/Dockerfile
I suggest to close this issue and add some docker images for testing with different distributions.
