### ISSUE TITLE
Mailing list link is 404

### ISSUE THREAD

**Issue by ferringb** [reorg/pg_repack#204]
The README.md points at http://pgfoundry.org/mailman/listinfo/reorg-general for the ML, but that list no longer exists.  It should either be updated or wiped.

**Comment by MasahikoSawada** [comment]
Thank you for the report.
I couldn't find the new link to the ML. Should we wipe it?

Also the link to pg_reorg project seems not to work. Maybe we can update it to http://ossc-db.github.io/pg_reorg/index.html

**Comment by ferringb** [comment]
Pardon- if you're asking me for my opinion, I have known.  I'm just a drive by noting that the links are broken ;)

**Comment by TysonAndre** [comment]
At the time of writing, the domain in question is supposedly a body building forum (pro gains), so removing it might make sense.

**Comment by dvarrazzo** [comment]
FIxed
