### ISSUE TITLE
correct pg_repack stop

### ISSUE THREAD

**Issue by OrangeFlag** [reorg/pg_repack#206]
Hello, how to correct stop pg_repack?

> Case: We had a database size swelling and until found out heart of trouble, launched pg_repak all over the base.
> It's help, but a lot of locks interfered with important replication, so i stop repack (Ctrl-C, SIGINT)
> And during the next replication of each table separately we have `WARNING: the table "table_name" already has a trigger called "repack_trigger"`. It's a big problem to cascade delete on our big base, so we just removed the trigger.

So, if you don't have mechanism of correct stop, maybe you add it?
On SIGINT - remove trigger, remove temporary tables if information about table files is not yet switch. Or otherwise drop old table and stop repack.

**Comment by dvarrazzo** [comment]
> So, if you don't have mechanism of correct stop, maybe you add it?

It wouldn't be reliable anyway. There are many other signals, and you can't do anything about a SIGKILL, or a machine crashed.

Just drop the extension and re-create it, and it will drop all the associated triggers.

**Comment by OrangeFlag** [comment]
@dvarrazzo It would be too long operation on large base sizes. No?

**Comment by schmiddy** [comment]
We do actually make an attempt to cleanup in the case of errors, and I'm pretty sure this is supposed to work in case of e.g. SIGINT: https://github.com/reorg/pg_repack/blob/d028e98437fe9cf13a5ba94898429c2cac4e2398/bin/pg_repack.c#L1855

**Comment by OrangeFlag** [comment]
@schmiddy thank you, I try to reproduce this behaviour after the weekend and I'll write you
