### ISSUE TITLE
undefined symbol: pqsignal

### ISSUE THREAD

**Issue by UserNotFound** [reorg/pg_repack#217]
I'm having trouble using pg_repack in PG 9.4 (9.5, 9.6, 10, an 11 work fine using the same process), and I can't figure out what introduced the change that is resulting in this error:

```
root@e460f9f6e252:/#   sudo -u postgres psql --command "CREATE EXTENSION pg_repack;"
CREATE EXTENSION

root@e460f9f6e252:/# sudo -u postgres pg_repack --dry-run
pg_repack: symbol lookup error: pg_repack: undefined symbol: pqsignal

root@e460f9f6e252:/# sudo -u postgres pg_repack --help
pg_repack: symbol lookup error: pg_repack: undefined symbol: pqsignal
```

Neither the version of postgres or pg_repack have apparently changed since this last worked for me Aug 28, so I'm at a bit of loss as to where this change got introduced. I'm using Debian Jessie, with versions:

postgresql-9.4                          9.4.24-1.pgdg80+1
postgresql-9.4-repack                   1.4.4-2.pgdg80+1

**Comment by Melkij** [comment]
Could you check your libpq version please? I think its related to this change: https://www.postgresql.org/message-id/flat/E1g5vmT-0003K1-6S%40gemulon.postgresql.org

**Comment by UserNotFound** [comment]
HI @Melkij, thanks for the quick reply - it looks like you're right on the money.  I ran into this last week, but just before the most two recent replies in the thread you linked to :(

The previous version I was on was 11.5-1.pgdg8, and now only 12.0-1.pgdg80+1 is available from `http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg/main`

**Comment by Melkij** [comment]
Try with explicit version for repository:
```
deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main 11
```
[Per wiki](https://wiki.postgresql.org/wiki/Apt/FAQ#I_want_libpq5_for_version_X.2C_but_there_is_only_version_Y_in_the_repository)

**Comment by UserNotFound** [comment]
Thanks @Melkij, pinning libpq to 11.* resolved my immediate need!

**Comment by Melkij** [comment]
this change of libpq [was reverted](https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=7ed1bcaed6ecbb0760169ea193cbe70071012576). So issue should be gone with next minor release 12.1

**Comment by justinpryzby** [comment]
@UserNotFound should close this issue  ?

**Comment by UserNotFound** [comment]
@justinpryzby I'll do just that.
