### ISSUE TITLE
stderr for logging?

### ISSUE THREAD

**Issue by nineonine** [reorg/pg_repack#218]
Greetings!

We are invoking `pg_repack` as a child process from Haskell application and for some reason the logs are always coming through stderr. Is this expected?

Another weirdness is that we always get this error message in stderr on each invocation:

```
could not find a "pg_repack" to execute
```

Any idea what this error might mean? Note that repack is actually running, but before it runs we always see this error. 

Thanks!

**Comment by nineonine** [comment]
Gentle ping!

**Comment by dvarrazzo** [comment]
Logs go to stderr as established practice since about 1970.

For the other error, it's something related to postgres executables: see

https://www.postgresql.org/message-id/E1VPJrB-00071y-RR@wrigleys.postgresql.org

**Comment by nineonine** [comment]
Got it. Thanks!
