### ISSUE TITLE
FATAL:  terminating connection due to idle-in-transaction timeout

### ISSUE THREAD

**Issue by nagaraju11** [reorg/pg_repack#222]
When I tried to repack my bloated table an error occurred:

FATAL:  terminating connection due to idle-in-transaction timeout
ERROR: query failed: SSL connection has been closed unexpectedly
DETAIL: query was: SAVEPOINT repack_sp1

and this error is occurring in large tables only, and current table size which is running about 700GB

/pg_repack --version
pg_repack 1.4.3

DB version: PostgreSQL 9.6.11 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.9.3, 64-bit

**Comment by Melkij** [comment]
Hello
You need disable idle_in_transaction_session_timeout. This is postgresql setting and it is disabled by default. pg_repack does not handle this case.

**Comment by nagaraju11** [comment]
Yes its disable.

show  idle_in_transaction_session_timeout;
- - -
0

Thanks

**Comment by Melkij** [comment]
Is it on the same user and database? I means such timeout may be per-user or per-database setting (`\drds` in psql)
`terminating connection due to idle-in-transaction timeout` is clearly related only to idle_in_transaction_session_timeout https://github.com/postgres/postgres/blob/REL9_6_11/src/backend/tcop/postgres.c#L3019

**Comment by nagaraju11** [comment]
Yes, I’m using same user.

It is working fine on small tables in size.

**Comment by nagaraju11** [comment]
yeah its working now.

I have disabled idle_in_transaction_session_timeout but did not reload the config file. its working fine after reloaded the server.

Thank you

**Comment by davidklika** [comment]
Hello. It is not very nice to reconfigure (especially production) database server before and after every db maintenance task. Would it be possible to set idle_in_transaction_session_timeout to zero locally in pg_repack sessions? (for version 9.6 and newer). Any comments? Thank you

**Comment by bukem** [comment]
Agree with @davidklika and I also have another question - why do we have idle_in_transaction timeout?
Thanks
