### ISSUE TITLE
PostgreSQL fails to drop pg_repack extension (1.4.3)

### ISSUE THREAD

**Issue by izinovik** [reorg/pg_repack#226]
Hello.

I'm using pg_repack 1.4.3. Looks like it failed to repack some tables in my database and now I'm stuck with inability to drop extension and start from scratch.
```
=# DROP EXTENSION pg_repack CASCADE ;
ERROR:  could not find tuple for trigger 1749583131
```

I decided to drop/create the extension because pg_repack constantly fails to repack my database:
```
INFO: repacking table "public.t1"
ERROR: query failed: ERROR:  type "pk_1358021427" already exists
DETAIL: query was: CREATE TYPE repack.pk_1358021427 AS (id integer)
```

Unfortunately I do not see such type pk_1358021427 in my database.

**Comment by justinpryzby** [comment]
Is pk_1358021427 in the repack.* (or other non-public) schema ?
You can check SELECT oid::regtype FROM [g_type WHERE typname='pk_...';

**Comment by MichaelDBA** [comment]
Question asked over 2 years ago and issue creator has not responded.  Closing...
