### ISSUE TITLE
Error creating functional index function does not exists

### ISSUE THREAD

**Issue by venkat0568** [reorg/pg_repack#228]
When pg_repack is creating functional indexes like below it is throwing an error. But when I ran the same CREATE INDEX command on actual table in public schema it worked fine. How do I fix this issue? 

CREATE INDEX index_27498 ON repack.table_16509 USING btree ("misc_util$mod_bucket"(account__id, 240)) TABLESPACE pg_default

```
LOG: Command finished in worker 0: CREATE INDEX index_27498 ON repack.table_16509 USING btree ("misc_util$mod_bucket"(account__id, 240)) TABLESPACE pg_default
WARNING: Error with create index: ERROR:  function misc_util$mod_bucket(bigint, integer) does not exist
LINE 1: ...EX index_27498 ON repack.table_16509 USING btree ("misc_util...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

**Comment by justinpryzby** [comment]
Is this still reproducible ?
Under what pg_repack version?
Do you have a "recipe" to reproduce it ?

**Comment by MichaelDBA** [comment]
This works fine with version 1.4.8 and PG14.  Also, Issue creator was asked over 2 years about details and no response given.  Closing this now...
