### ISSUE TITLE
Error when trying to add pg_repack

### ISSUE THREAD

**Issue by lucas1** [reorg/pg_repack#232]
Hi everyone,

I'm using Centos 7 and PostgreSQL 11.7

see error:
psql -U postgres -c "CREATE EXTENSION pg_repack" -d db
ERROR:  could not load library "/usr/pgsql-11/lib/pg_repack.so": /usr/pgsql-11/lib/pg_repack.so: undefined symbol: CatalogIndexInsert

thanks.

**Comment by dvarrazzo** [comment]
And what version of pg_repack? Can you try reinstalling it?

**Comment by lucas1** [comment]
Version 1.4.5, I can try.

**Comment by lucas1** [comment]
See logs:

$ make
make[1]: Entering directory `/root/pg_repack-1.4.5/bin'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/root/pg_repack-1.4.5/bin'
make[1]: Entering directory `/root/pg_repack-1.4.5/lib'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/root/pg_repack-1.4.5/lib'
make[1]: Entering directory `/root/pg_repack-1.4.5/regress'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/root/pg_repack-1.4.5/regress'

$ PG_CONFIG=/usr/pgsql-11/bin/pg_config make install
make[1]: Entering directory `/root/pg_repack-1.4.5/bin'
/usr/bin/mkdir -p '/usr/pgsql-11/bin'
/usr/bin/install -c  pg_repack '/usr/pgsql-11/bin'
make[1]: Leaving directory `/root/pg_repack-1.4.5/bin'
make[1]: Entering directory `/root/pg_repack-1.4.5/lib'
/usr/bin/mkdir -p '/usr/pgsql-11/lib'
/usr/bin/mkdir -p '/usr/pgsql-11/share/extension'
/usr/bin/mkdir -p '/usr/pgsql-11/share/extension'
/usr/bin/install -c -m 755  pg_repack.so '/usr/pgsql-11/lib/pg_repack.so'
/usr/bin/install -c -m 644 .//pg_repack.control '/usr/pgsql-11/share/extension/'
/usr/bin/install -c -m 644  pg_repack--1.4.5.sql pg_repack.control '/usr/pgsql-11/share/extension/'
/usr/bin/mkdir -p '/usr/pgsql-11/lib/bitcode/pg_repack'
/usr/bin/mkdir -p '/usr/pgsql-11/lib/bitcode'/pg_repack/ '/usr/pgsql-11/lib/bitcode'/pg_repack/pgut/
/usr/bin/install -c -m 644 repack.bc '/usr/pgsql-11/lib/bitcode'/pg_repack/./
/usr/bin/install -c -m 644 pgut/pgut-spi.bc '/usr/pgsql-11/lib/bitcode'/pg_repack/pgut/
cd '/usr/pgsql-11/lib/bitcode' && /usr/lib64/llvm5.0/bin/llvm-lto -thinlto -thinlto-action=thinlink -o pg_repack.index.bc pg_repack/repack.bc pg_repack/pgut/pgut-spi.bc
make[1]: Leaving directory `/root/pg_repack-1.4.5/lib'
make[1]: Entering directory `/root/pg_repack-1.4.5/regress'
make[1]: Nothing to be done for `install'.
make[1]: Leaving directory `/root/pg_repack-1.4.5/regress'

**Comment by lucas1** [comment]
Can help me?

**Comment by lucas1** [comment]
Solved with:
$ PG_CONFIG=/usr/pgsql-11/bin/pg_config make
$ PG_CONFIG=/usr/pgsql-11/bin/pg_config make install 

before I was executing:
$ make
$ PG_CONFIG=/usr/pgsql-11/bin/pg_config make install 

Thanks.

**Comment by dvarrazzo** [comment]
Yes, so there was a mixup between what you build and what you install.

Do you think documentation can be improved about it? Would you like to submit a documentation patch?

Thank you very much
