### ISSUE TITLE
Add the ability to use COPY with the FREEZE option

### ISSUE THREAD

**Issue by levinsv** [reorg/pg_repack#233]
Hi.
Instead of INSERT use COPY with the FREEZE option. This is useful for large tables.

**Comment by Melkij** [comment]
Hello
copy has no syntax to copy data from one table to another table. So we need call `copy from table to stdout` in one connection, open yet another connection with `copy from stdin` and transfer the entire amount of data through the application. Seems expensive. However, I think it is a good idea to add the ability to limit insert throughput. Currently I have no plans to write such PR.

**Comment by levinsv** [comment]
You can do this through a temporary file.
More or less like this:
`table.copy_data = "copy (select f1, f2, f3 from ONLY archive_table order by f3, f2) to '/tmp/tmp_repack.file'; copy repack.table_17031 from '/tmp/tmp_repack.file' FREEZE";`
An important point: the table will no longer be overwritten when SELECT is executed.

I tested this idea today. All rows are frozen.
But doing Vacuum overwrites all pages by setting the PD_ALL_VISIBLE bit.

There is no more reason to use COPY.
