### ISSUE TITLE
Support for pausing and resuming an incomplete repack.repack_apply? (repack_apply())

### ISSUE THREAD

**Issue by TysonAndre** [reorg/pg_repack#240]
(e.g. add a `pg_repack --resume` flag which would allow resuming if the table_$id and log_$id and triggers already existed)

It may be useful to resume a repack that was terminated for reasons such as:

1. The client unexpectedly stopped (jenkins timeout, the machine the client was running on turned off or lost network connectivity, an unexpected crash, etc)
2. The server was under high load and a long-running repack was stopped to reduce that load
3. To resume the repack with different configuration options or with a different/newer pg_repack release (e.g. different parallelism for index rebuilds, different applied row thresholds for starting the final switch, etc)

From the documentation at https://reorg.github.io/pg_repack/ , and a quick look at https://reorg.github.io/pg_repack/, I didn't see any references or previous feature requests to resume/unpause a repack.

I'd assume this could be safe under the following preconditions:
1. The repack.log_$id and repack.table_$id and the triggers already exist
2. The $id is the correct id for each of the tables in question
3. Nothing else is already running repack_apply (not sure if it's practical to check for this. A heuristic might be to check if the first element in the repack log  (if one exists) gets changed or removed after a short timeout, e.g. 10 seconds)

The repack_apply phase I'm referring to is the one when `LOG: (query) SELECT repack.repack_apply($1, $2, $3, $4, $5, $6)` is logged for a given table id

**Comment by dvarrazzo** [comment]
I wouldn't do such a thing.  I'd rather restart the operation rather than hoping it is left in a resumable state. I wouldn't trade consistency for speed.

**Comment by TysonAndre** [comment]
Understandable, this is a bit of an edge case and there's no guarantee pg_repack 1.x.y would be able to resume 1.a.b. The other reasons I'd originally had to suggest this were:

1. I think pg_repack is already dropping a few of the updates/inserts/deletes at the end before the final switch (which might be fixable) - even if <= 20 are applied in the last batch, a few more rows get updated/deleted/inserted to the original table before the switch
2. If the copying phase takes an hour or so to complete, it's already able to process rows that are an hour out of date
