### ISSUE TITLE
HELP: SSL SYSCALL error: EOF detected

### ISSUE THREAD

**Issue by ricardolpd** [reorg/pg_repack#245]
Apologies if this is the wrong place to post this, but i am trying to repack in a db hosted in ibmcloud but i keep getting the following, what is causing this, and how do i fix it?

```
ERROR: query failed: SSL SYSCALL error: EOF detected
DETAIL: query was: INSERT INTO repack.table_16475 SELECT id,creation_date,cms_id,url,html,text,findings,last_modified,published_date FROM ONLY public.articles
ERROR: query failed: SSL SYSCALL error: EOF detected
DETAIL: query was: SELECT repack.repack_drop($1, $2)
ERROR: query failed: SSL SYSCALL error: EOF detected
DETAIL: query was: SELECT repack.repack_drop($1, $2)
ERROR: query failed: SSL SYSCALL error: EOF detected
DETAIL: query was: SELECT repack.repack_drop($1, $2)
ERROR: query failed: SSL SYSCALL error: EOF detected
DETAIL: query was: SELECT repack.repack_drop($1, $2)
ERROR: query failed: SSL SYSCALL error: EOF detected
DETAIL: query was: SELECT repack.repack_drop($1, $2)
NOTICE:  table "log_16475" does not exist, skipping
NOTICE:  type "repack.pk_16475" does not exist, skipping
NOTICE:  trigger "repack_trigger" for relation "public.articles" does not exist, skipping
```

These are the arguments used to attempt to repack the table:

`--no-superuser-check --no-kill-backend --table=articles ` 

As it stands i have gotten this error twice, and the instance has doubled in size because of it, i would appreciate any help.

**Comment by dvarrazzo** [comment]
It seems they are dropping your connections. Maybe you could try setting up some TCP keepalive in the connection string - see relevant options in the postgres documentation and the PGOPTIONS env var.

If this works please let us know. However you should rather ask ibmcloud support if they are dropping apparently inactive connections.
