### ISSUE TITLE
Ignore (auto)vacuums in SQL_XID_SNAPSHOT check

### ISSUE THREAD

**Issue by schmiddy** [reorg/pg_repack#25]
One frustration I've encountered while running pg_repack in a busy production database is that concurrent autovacuums of other tables can show up in the SQL_XID_ALIVE query, which will think it needs to wait potentially many hours for the autovacuum to finish.

I believe it should be safe for us to simply ignore VACUUMs and autovacuums of other tables in the SQL_XID_SNAPSHOT query.

**Comment by jmehnle** [comment]
I'm being bitten by this as well. Is this necessary?

**Comment by amitlan** [comment]
I guess this is what recent PR #87 is for.

**Comment by schmiddy** [comment]
Merged #87.
