### ISSUE TITLE
Unable to update existing extension

### ISSUE THREAD

**Issue by chobostar** [reorg/pg_repack#252]
after update pg_repack package:
```
alter extension pg_repack update;
ERROR:  extension "pg_repack" has no update path from version "1.4.5" to version "1.4.6"
```
as workaround - drop and create extension

**Comment by Melkij** [comment]
Hello
Yes, pg_repack does not support extension update scripts.

This is [documented here](https://reorg.github.io/pg_repack/):

> ERROR: extension 'pg_repack V1' required, found extension 'pg_repack V2'
>    The SQL extension found in the database does not match the version required by the pg_repack program.
>    You should drop the extension from the database and reload it as described in the installation section.
