### ISSUE TITLE
Get ./pgut/pgut.h:13:10: fatal error: 'c.h' file not found when try compile pg_repack-1.4.5 with postgresql 12.4

### ISSUE THREAD

**Issue by YuliaSim** [reorg/pg_repack#254]
Hello,
I can't compile pg_repack-1.4.5 with postgresql v12.4
I installed postgresql using the following command: brew install postgres@12, I succeeded to use pg_config.
When I tried to make the pg_repack folder I got the following error:
./pgut/pgut.h:13:10: fatal error: 'c.h' file not found 

When I tried to install posgresql v13 and pg_repack-1.4.6 , it worked. 
I tried to make pg_repack-1.4.5 with postgresql v13 and it failed. 

My remote db is of v12 and uses pg_repack extension of 1.4.5, therefore I need to be able to execute pg_repack of the same version as in server. Otherwise, I get the error during the execution of the pg_repack.

**Comment by dvarrazzo** [comment]
`c.h` is an include file from postgres, so you need to install postgresql-server-dev-13, or whatever the package is called in your package manager.
