### ISSUE TITLE
Tables disappear if pg_repack process is stopped/killed

### ISSUE THREAD

**Issue by prem-fissionhq** [reorg/pg_repack#255]
Source: pgbouncer machine
Dest: PostgreSQL RDS 
Table Size: 1.5 TB

I'm running the pg_repack process from a PGbouncer machine which is connected with the PostgreSQL RDS machine. 
Since, the tables sizes are _approx: 1.2 TB to 1.5 TB_ the job was running even **after 20+ hours gone**. So I assumed something is wrong and _killed the pg_repack process_. As soon as I did that all **tables in the database got disappeared** ini the pgboucner machine. Due to which the application went down, which is critical issue. 
**Resolution**: reload pgboucner config and all the tables came back including the database. I.e got restored from RDS to pgbouncer machine. 

I have reproduced this issue multiple items and found that if you kill/stop the running pg_repacking process then 
1. we will ran into this issue. 
2. permission denied errors while inserting data into the pg_repack log tables.

How can we resolve this issue? Please suggest. thanks

**Comment by dvarrazzo** [comment]
> I'm running the pg_repack process from a PGbouncer machine

This sounds like a really, really bad idea.

pg_repack is not compatible with pgbouncer.

**Comment by prem-fissionhq** [comment]
@dvarrazzo thank you very much for your response. 
So, 
1. do you want us to execute directly on the RDS machine and there we’re not going to face any such issues? 
2. Incase of any interruption I have to follow the process of dropping extension and recreate them?

**Comment by schmiddy** [comment]
FWIW pg_repack is "supported" on RDS (at least on vanilla PostgreSQL+RDS, not Aurora, AFAIK) - the only change we had to make was back in #114. RDS has allowed pg_repack as an [officially supported](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Appendix.PostgreSQL.CommonDBATasks.html#Appendix.PostgreSQL.CommonDBATasks.pg_repack) extension on their end. 

 @prem-fissionhq  - it really sounds like there is something unusual going on in your environment if the tables "disappear" until you reload pgBouncer's config. It will help if you could troubleshoot the issue without pgBouncer in the middle - I think that running the repack command from the machine that pgBouncer runs on is OK. Are you having pg_repack connect directly to RDS, or does its connection go through the pgBouncer machine first? If it's the latter, try not to do that -- it is just going to complicate the troubleshooting. Then, if you see something unusual, like tables "disappear", try to verify the behavior with a `psql` client also connecting directly to RDS (again, should be OK to run the `psql` client from the pgBouncer host, as long as you connect directly to the database).

**Comment by dvarrazzo** [comment]
> RDS has allowed pg_repack as an officially supported extension on their end

That's very sweet of them, but it's not like they have ever contributed to the project: not with code, not with funding, not in any other form. So, as far as I'm concerned, if someone has issues regarding running pg_repack on RDS, they should solve it with Amazon, not with repack.

**Comment by prem-fissionhq** [comment]
> FWIW pg_repack is "supported" on RDS (at least on vanilla PostgreSQL+RDS, not Aurora, AFAIK) - the only change we had to make was back in #114. RDS has allowed pg_repack as an [officially supported](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Appendix.PostgreSQL.CommonDBATasks.html#Appendix.PostgreSQL.CommonDBATasks.pg_repack) extension on their end.
> 
> @prem-fissionhq - it really sounds like there is something unusual going on in your environment if the tables "disappear" until you reload pgBouncer's config. It will help if you could troubleshoot the issue without pgBouncer in the middle - I think that running the repack command from the machine that pgBouncer runs on is OK. Are you having pg_repack connect directly to RDS, or does its connection go through the pgBouncer machine first? If it's the latter, try not to do that -- it is just going to complicate the troubleshooting. Then, if you see something unusual, like tables "disappear", try to verify the behavior with a `psql` client also connecting directly to RDS (again, should be OK to run the `psql` client from the pgBouncer host, as long as you connect directly to the database).

@schmiddy thanks for the suggestions... yes we did it in the same way and we are using pg_repack: 1.4.3 version. 
For us everything seems to be working even from pg_bouncer but if things going wrong like `system shutdown, process kill while running (for anyreason)`, the tables gets disappear and we also ran into permission denied on log_repack tables. So, we were need of your help. we checked pgbouncer, pg_repack and syslog but couldn't find the any clue.

yes, you're are correct. we are connecting RDS via pgbouncer. As you suggested we will try running on RDS directly. 

@dvarrazzo yes, we did that as well, waitiing for their response. 

thank you!

**Comment by prem-fissionhq** [comment]
@schmiddy @dvarrazzo one more question what is the best way to run pg_repack on the tables > 1 TB? (~ 5-6 tables and each of them are of > 1 TB to < 2TB)
As I mentioned above the process was running for more than 20+ hours and I read that we might run into `pg_repack holds the ACCESS EXCLUSIVE lock while waiting for the auto vacuum to finish`. can you please help here on what is the best way to handle this situation? thanks
