### ISSUE TITLE
Avoid autovacuums of the target table

### ISSUE THREAD

**Issue by schmiddy** [reorg/pg_repack#26]
Another frustration we've experienced while running pg_repack in a busy production database is having autovacuum kick in for the table while in the middle of repacking -- not such an unlikely scenario for a busy table. This is a waste of precious I/O at best, and can also cause a nuisance for lock_exclusive() to cancel/terminate.

It would be nice if we could simply do an ALTER TABLE ... SET autovacuum_enabled=false on the target table while we're repacking. Restoring the original value in the case that pg_repack gets killed might take some thought, though.

**Comment by depesz** [comment]
autovacuum of the target table is one thing, but I noticed another problem with autovacuum. I repack a table, it finishes it's work, and has to switch tables, but there is some kind of autovacuum process, and now pg_repack has to wait for it to finish. It has to wait for all backends, but other transactions usually end in 1 minute or so, while autovacuum can take many hours.

So, I'd like to ask for an option that would allow pg_repack to either ignore, or kill, autovacuums that block table swap.

Would it be possible?

**Comment by schmiddy** [comment]
Yes, that's been a nuisance for me too. Seems like it would probably be safe to just ignore autovacuum workers in our SQL_XID_SNAPSHOT query.

**Comment by gabegorelick** [comment]
> autovacuum of the target table is one thing, but I noticed another problem with autovacuum. I repack a table, it finishes it's work, and has to switch tables, but there is some kind of autovacuum process, and now pg_repack has to wait for it to finish.

I've experienced this when a wraparound autovacuum was already running before starting pg_repack. The worst part is pg_repack holds the ACCESS EXCLUSIVE lock while waiting for the autovacuum to finish. But this can take days! In the meantime, your table is locked.

**Comment by gabegorelick** [comment]
> Seems like it would probably be safe to just ignore autovacuum workers in our SQL_XID_SNAPSHOT query.

I believe https://github.com/reorg/pg_repack/pull/87 implemented this. Although not sure why we see extended locking while waiting for vacuum to finish, but see https://github.com/reorg/pg_repack/issues/95 for that.

**Comment by MichaelDBA** [comment]
Closing this issue since it was merged.
