### ISSUE TITLE
repack_disable_autovacuum missing must_be_superuser call

### ISSUE THREAD

**Issue by fluggo** [reorg/pg_repack#266]
I was browsing the source code, and I noticed that all of the extension's C functions make a call to must_be_superuser() except [repack_disable_autovacuum](https://github.com/reorg/pg_repack/blob/ebc8a425fcabc06d62a1c9b51fbc3a5f460b2baa/lib/repack.c#L1097). I did a quick test and, under the default schema permissions, it doesn't look like I can run the function as an ordinary user. Nevertheless, I thought I should bring it to your attention.

**Comment by za-arthur** [comment]
The function executes `ALTER TABLE` using SPI and PostgreSQL will check if a user has necessary permissions on the table. Here is an example if the function is called by a non-superuser (the user should have permission to use the function):

```
=> select repack.disable_autovacuum('repack_table'::regclass);
ERROR:  must be owner of table repack_table
CONTEXT:  SQL statement "ALTER TABLE public.repack_table SET (autovacuum_enabled = off)"
```

Closing the issue. Please feel free to re-open it if necessary.
