### ISSUE TITLE
does pg_repack support online repack operations for partitioned tables ? 

### ISSUE THREAD

**Issue by hseyindemir** [reorg/pg_repack#269]
Does pg_repack tool support online repack operations for a partitioned table ? 

For example, i have some tables which has high bloat ratio and these tables are partitioned tables

Can i use pg_repack for this tables ?

**Comment by Melkij** [comment]
Hello
You can use pg_repack on individual partitions (not on the head of partitioned table).

**Comment by hseyindemir** [comment]
Hello, 

As you said and i understand, we can apply pg_repack on an individual partitioned table... 

I will try and share the results. 

Thanks.

**Comment by MichaelDBA** [comment]
Closed due to lack of response to validate the solution.
