### ISSUE TITLE
Can't build pg_repack on Ubuntu 12.04 with postgresql installed from apt

### ISSUE THREAD

**Issue by jfrost** [reorg/pg_repack#27]
See longer write-up here:

http://www.postgresql.org/message-id/7AE8BFFE-55C7-4B95-86F8-DEE7C507B33D@pgexperts.com

tl;dr; version: if you are runnning anything less than 9.3 on debian derivatives from apt.postgresql.org, pg_repack doesn't build correctly because libpq-dev is only available in the 9.3 version.

Any idea how to make that work?

**Comment by dvarrazzo** [comment]
hey @jfrost

I've read in [your message](http://www.postgresql.org/message-id/CE7218A3-CF70-439D-AF3A-56A2F32F742B@pgexperts.com) that you have solved this problem. Could you please report a solution here and maybe we can close the issue (which really seems a pgdg one, not pg_repack's).

Thank you.

**Comment by keithf4** [comment]
We had this issue as well since we're running 9.2 on 12.04. The solution was to pin the version of postgresql that is obtained from pgdg to whatever version of 9.2 that we are running. Can do this by creating a file in /etc/preferences.d/ with the following (or whatever version you need)
```
kfiske@db1:/etc/apt/preferences.d$ cat postgresql 
Package: postgresql-* libpq5 libpq-dev
Pin: version 9.2.10-*
Pin-Priority: 501
```

**Comment by jfrost** [comment]
Oh yes, sorry for not following up here earlier!

So, the problem is that by default you get the latest and greatest libpq-dev installed (would be 9.4.x at the time of this writing), but if you are running a different postgresql version (say 9.2 in my original report), your pg_repack installation will fail.

The solution is that you need to add the version specific repo to your apt sources line, so it looks like:

`deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main 9.2`

Then you need to `apt-get install libpq-dev=9.2\* libpq5=9.2\*`

and then `pgxn install pg_repack --sudo` works great.

**Comment by dvarrazzo** [comment]
Is there anything we can mention in the doc for the future?
