### ISSUE TITLE
Uncompleted repack operation

### ISSUE THREAD

**Issue by fatihmtekin** [reorg/pg_repack#270]
Firstly, thanks in advance for your help.
I use 3 node PostgreSQL 12.6 on RHEL 7.9 with patroni. 
I installed pg_repack rpm package. Then, I run the command for a specific table, " pg_repack -t geo.location ". The information logs are below;
INFO: repacking table "geo. location"
NOTICE: Waiting for 1 transactions to finish. First PID: 45659
NOTICE: Waiting for 1 transactions to finish. First PID: 45659
NOTICE: Waiting for 1 transactions to finish. First PID: 45659
NOTICE: Waiting for 1 transactions to finish. First PID: 45659
NOTICE: Waiting for 1 transactions to finish. First PID: 45659
NOTICE: Waiting for 1 transactions to finish. First PID: 45659
NOTICE: Waiting for 1 transactions to finish. First PID: 45659

I terminated the query with PID 45659. The pg_repack operation is still running for 2 hours. Table info is;
live tuple: 19160
dead tuple: 11702185
and pg_repack tables are;
log_1659472 : live tuple 2517, dead tuple 1722863
table_1659472 : live tuple 23204, dead tuple 988939

Is it dangerous to terminate this process? Or what should I do?

**Comment by Melkij** [comment]
Please check pg_stat_activity system view. Interest things:
- what do the connections to the database from pg_repack do, wait for something? Which query is running? (please note there are multiple connections from pg_repack)
- another activity, especially wraparound autovacuum on `geo.location`?

it should be safe to terminate pg_repack process

**Comment by fatihmtekin** [comment]
pg_repack transaction is active. Only one connection is active from pg_repack, and one idle-in-transaction connection, also there is no waiting. Autovacuum is enable on geo.location table. Also geo.location table autovacuum cost limit parameter : autovacuum_vacuum_cost_limit=1000

pg_stat_activity info :

titanium=# select * from pg_stat_activity where application_name = 'pg_repack';
-[ RECORD 1 ]----+---------------------------------------------------
datid            | 49624
datname          | titanium
pid              | 131051
usesysid         | 10
usename          | postgres
application_name | pg_repack
client_addr      | 
client_hostname  | 
client_port      | -1
backend_start    | 2021-05-03 09:55:46.205435+03
xact_start       | 2021-05-03 18:11:31.551786+03
query_start      | 2021-05-03 18:11:31.551873+03
state_change     | 2021-05-03 18:11:31.551873+03
wait_event_type  | 
wait_event       | 
state            | active
backend_xid      | 
backend_xmin     | 3637833891
query            | SELECT repack.repack_apply($1, $2, $3, $4, $5, $6)
backend_type     | client backend
-[ RECORD 2 ]----+---------------------------------------------------
datid            | 49624
datname          | titanium
pid              | 131052
usesysid         | 10
usename          | postgres
application_name | pg_repack
client_addr      | 
client_hostname  | 
client_port      | -1
backend_start    | 2021-05-03 09:55:46.212646+03
xact_start       | 2021-05-03 09:55:47.368986+03
query_start      | 2021-05-03 09:55:47.36957+03
state_change     | 2021-05-03 09:55:47.386147+03
wait_event_type  | Client
wait_event       | ClientRead
state            | idle in transaction
backend_xid      | 
backend_xmin     | 
query            | LOCK TABLE geo.location IN ACCESS SHARE MODE
backend_type     | client backend

**Comment by schmiddy** [comment]
That looks like pg_repack is running. Are the rows in the `log_` table decreasing? Is there a lot of activity modifying the main geo.location table? If there's still a lot of other writes happening to the geo.location table, pg_repack may not be able to make progress quickly enough to finish and perform its swap. If it's only a few thousand rows left in the log_ table, try cutting off whatever is doing all the writes to the table for a minute or two to let pg_repack finish its work and swap.

**Comment by fatihmtekin** [comment]
The rows number increasing continuously in repack.log_ table. The table size is 3768MB.  geo. location table is under heavy update and delete operations. There are 650k delete transactions and 250k update operations for the last 1 hour. The geo. location table is the most critical table in the production system, so there is no chance of cutting off the transactions.
As I was writing this message, the size of the repack.log_ table became 3862MB.
Is terminate the pg_repack operation the only option?

**Comment by schmiddy** [comment]
Those table sizes aren't too bad, but pg_repack may struggle to complete if you have sustained high I/O load to the table relative to what your database can handle. The table size of the log_ table is less important than the raw row count (live tuples) in that table. If that count is growing consistently even as repack_apply() runs, it means pg_repack won't be able to finish the job. If that's the case, yeah, better to kill it (Control-C) now rather than waiting more hours and have the log_ table grow even bigger.

**Comment by fatihmtekin** [comment]
There are 11908863 dead tuples and 3369369 live tuples in the log_ table. As you said, I think there is no need to wait. I terminated the repack operation.
Thank you again for your help.
