### ISSUE TITLE
must have a primary key or not-null unique keys when INCLUDE columns

### ISSUE THREAD

**Issue by pguser4ever** [reorg/pg_repack#282]
pg_repack version 1.4.6

Running pg_repack on table (in this case a partition) generate an error with pk and INCLUDE column

pg_repack -h dbserver1 
--no-kill-backend  --table=dummy.parttable2_2021_07_13 -j 4 --order-by=sdrid,sdrtimestamp

NOTICE: Setting up workers.conns
WARNING: relation "dummy.parttable2_2021_07_13" must have a primary key or not-null unique keys

pk: 
PRIMARY KEY, btree (sdrid, sdrtimestamp) INCLUDE (applicationserverid)   

reorg tables without include columns works fine 

If we add NOT NULL to INCLUDE column i primary key it works 
My assumption was that INCLUDE columns is not a part of the primary key and that pg_repack should just ignore 
the INCLUDE column/columns in this case and only use pk columns for sorting

**Comment by sgrinko** [comment]
We really need support for this opportunity!
What is the status for now?

**Comment by za-arthur** [comment]
Should be fixed by https://github.com/reorg/pg_repack/pull/376
