### ISSUE TITLE
pg_repack Leaks Passwords to Logs on Connection Error

### ISSUE THREAD

**Issue by danielmerken** [reorg/pg_repack#285]
On connection error, the following is printed:

> ERROR: could not connect to database with "dbname=******** password=******** ": could not connect to server: Connection refused

I've redacted the dbname and password, but they are printed in plaintext to the log. I noticed this in version 1.4.5.

**Comment by dvarrazzo** [comment]
You know that you can use the PGPASSWORD env var, right?

**Comment by mikkorantalainen** [comment]
As it's expected that connection / info string contains credentials, it should not be ever logged. Log the extracted info (e.g. database name should not be a secret) that doesn't contain credentials. The environment variable can be used *as a workaround* but it's not a correct fix for this issue.

**Comment by danielmerken** [comment]
We initially noticed this issue when running PG repack using the PGPASSWORD env var, so I don't believe it avoids this issue.

**Comment by andreasscherbaum** [comment]
#286 fixes this issue.
