### ISSUE TITLE
How much resources (memory, CPU) does `pg_repack` require?

### ISSUE THREAD

**Issue by moltar** [reorg/pg_repack#289]
Hi,

I have checked the docs and issues, but haven't found any recommendations for resource allocation for (memory, CPU) for `pg_repack`.

Does repack ever load a large amount of data in memory on the client-side or does all of the heavy lifting happen on the server-side?

And thank you for maintaining this amazing extension!

**Comment by Melkij** [comment]
Hello
The executable binary pg_repack is just an observer and command module. Takes almost no resources by itself. All heavy operations are handled inside postgresql. Most noticeable parts are `insert ... select` while copying table data, `create index`, trigger to support concurrent table writes and apply procedure for this log table - all running inside DBMS.
Therefore tuning maintenance_work_mem and max_parallel_maintenance_workers (for btree) makes sence for index creation. Other parts currently are single-threaded. Usually `wal_compression = on` slows down pg_repack, but also reduces I/O spikes.

**Comment by moltar** [comment]
Thank you, @Melkij!

> The executable binary pg_repack is just an observer and command module. 

I thought so, and just wanted to confirm that!

I will try to run `pg_repack` with minimal resources available (512 MiB on Fargate) and report back!

**Comment by moltar** [comment]
Was able to run a light workload successfully on 256 (.25 vCPU) and memory 512 (0.5 GB). :tada:

Will continue to test this, and if I run into issues, I'll comment.

Will close the issue for now, as it's not really an issue.
