### ISSUE TITLE
permission denied for schema repack with superuser

### ISSUE THREAD

**Issue by K3ndu** [reorg/pg_repack#296]
```
db=# create extension pg_repack;
ERROR:  permission denied for schema repack
```
```
db=# select current_user;
 current_user
--------------
 postgres
```

`postgres                            | Superuser, Create role, Create DB, Replication  | {localusers}`              

Any ideas what might be wrong?
pg_repack is latest greatest 1.4.7

**Comment by schmiddy** [comment]
Can you share what was wrong @K3ndu ?

**Comment by K3ndu** [comment]
> Can you share what was wrong @K3ndu ?

Looks like someone had messed up the permissions on postgres user. Somehow giving superuser permission to database owner(which is not postgres user) resolved the problem for me.
