### ISSUE TITLE
Does pg_repack have database mode

### ISSUE THREAD

**Issue by yinan8128** [reorg/pg_repack#300]
Hi,

pg_repack can be run by linux os cmd, does pg_repack also have database mode please?

We use patroni cluster, if run linux os command to trigger pg_repack then need to check which node is leader node and maintain cronjob in os level and so on. so if pg_repack have database mode can run in database level in leader node then is helpful, thanks

**Comment by yinan8128** [comment]
Hi,

Any update please? Thanks

**Comment by xzilla** [comment]
ISTM you must already have some kind of service discovery to determine which node is the primary for all other apps, so you should re-use that for pg_repack cli.

**Comment by SpokeyWheeler** [comment]
I'd quite like this as well. It would be great to run pg_repack from pg_cron.

**Comment by xzilla** [comment]
After reflecting on this, I wonder if the original request was more along the lines of having pg_repack run as a background worker with its own scheduling mechanism that could also do read-write verification, which would eliminate the need for cron and worrying about which node was the primary. Interesting idea, but the amount of work needed to incorporate that seems monumental given that other solutions to solve this problem already exist. 

As mentioned, if you want to run repack from cron but don't want to have to update the cron job when the leader changes, you can set up DNS or similar mechanisms (ie. whatever method you use to update a web host / application to know how to talk to the new primary) which can be updated after a failover, and point pg_repack at that host.

Similarly, if you want to eliminate the use of cron, you should look into pg_cron or pg_timetable.

**Comment by SpokeyWheeler** [comment]
But how would I run pg_repack from pg_cron?

**Comment by MichaelDBA** [comment]
**pg_cron** has no plans to integrate running **pg_repack** as an OS-driven command.  See closed issue, [(https://github.com/citusdata/pg_cron/issues/177)](https://github.com/citusdata/pg_cron/issues/177)
