### ISSUE TITLE
pg_repack to accept not only 'not null' column property but also 'not null' check constraint on the unique index column

### ISSUE THREAD

**Issue by Soni-Harriz** [reorg/pg_repack#304]
Hi,
Currently I would like to repack huge table that has no primary key. The issue is that I use old postgres installation, which adding primary key cannot be done without having access exclusive locks for long time. I already add unique index and not null check constraint on that column. But still pg_repack wants 'not null' on column properties. So, I try to hack a little in primary_keys view, so pg_repack also consider 'not null' check constraint on unique index column. It works for me, but I think it would need more work to make it work better. I only have little knowledge on pg_catalog tables. So, here's I dealt with it.

```
create or replace view repack.primary_keys as SELECT tmp.indrelid,
    min(tmp.indexrelid) AS indexrelid
   FROM ( SELECT pg_index.indrelid,
            pg_index.indexrelid
           FROM pg_index
          WHERE pg_index.indisunique AND pg_index.indisvalid AND pg_index.indpred IS NULL AND (0 <> ALL (pg_index.indkey::smallint[])) AND NOT (EXISTS ( SELECT 1
                   FROM pg_attribute INNER JOIN pg_constraint ON pg_constraint.conrelid = pg_attribute.attrelid
                  WHERE pg_attribute.attrelid = pg_index.indrelid AND pg_constraint.contype = 'c' AND pg_constraint.convalidated AND (pg_attribute.attnum = ANY (pg_index.indkey::smallint[])) AND (NOT pg_attribute.attnotnull AND NOT pg_catalog.pg_get_constraintdef(pg_constraint.oid, true) = concat('CHECK (', pg_attribute.attname, ' IS NOT NULL)') )))
          ORDER BY pg_index.indrelid, pg_index.indisprimary DESC, pg_index.indnatts, pg_index.indkey) tmp
  GROUP BY tmp.indrelid;
```

**Comment by Melkij** [comment]
Hello
The correct way would look like this: https://github.com/postgres/postgres/blob/REL_14_2/src/backend/commands/tablecmds.c#L7299
But I wouldn't want to copy the relevant code into pg_repack. It will complicate the support for future versions. But actually needed only for older versions of postgresql up to 12, which will soon be EOL (10 this year, 11 next year). In postgresql 12 my patch (code above) was merged and `alter table .. set not null` will not read the entire table if there is a valid check constraint. So `set not null` is no longer a big problem.

PS: probably [pgcompacttable](https://github.com/dataegret/pgcompacttable) may help in your case.

**Comment by andreasscherbaum** [comment]
As @Melkij pointed out, this should not go into pg_repack, as it changes the scope of the tool.
