### ISSUE TITLE
Use pg_repack for upgrading PKs from int4 to int8 - take 2

### ISSUE THREAD

**Issue by davidboden** [reorg/pg_repack#306]
Suggesting a different approach to getting new columns full of data, previously discussed in https://github.com/reorg/pg_repack/issues/197

I understand that the column metadata before and after the repack need to the the same. Would it be possible to carry out a multi-step process but use `pg_repack` in the middle to do the heavy lifting?

- Alter your table and add another nullable column with the target datatype.
- Create a "before insert" trigger which copies data from column_a into column_b whenever new tuples get added.
- Run `pg_repack` in such a way that it uses the trigger to generate values for column_b for all historical rows.
- Alter the table to set column_b to be NOT NULL.
- Drop column_a and rename column_b to column_a.

Sorry if this has already been considered or can't work with `pg_repack`. I've manually done these steps many times myself, but have to run a slow, batched update to give column_b all the right data. Then I have to repack the table at the end to get rid of all the dead tuples...

**Comment by andreasscherbaum** [comment]
This is outside the scope of pg_repack. This would transform pg_repack into a full migration tool.

Another tool which can do this can include pg_repack in the process, but pg_repack itself should not be extended to do this.

**Comment by andreasscherbaum** [comment]
pg_repack still has to deal with checking all the compatibilities. Plenty of code needs to be changed to not create the destination table, but verify that it is there. Also requires quite a few test cases to make sure all of this is working.

While I see that such a feature can be helpful for certain migration cases, it's still way outside of the pg_repack scope.

**Comment by MichaelDBA** [comment]
I would agree that stuff like this is way outside the scope of maintaining this vacuuming tool.

**Comment by simi** [comment]
> I would agree that stuff like this is way outside the scope of maintaining this vacuuming tool.

IMHO pg_repack is currently far away from being just "vacuuming tool". But ok, message clear. Thanks for the info.
