### ISSUE TITLE
Help with Issues?

### ISSUE THREAD

**Issue by MichaelDBA** [reorg/pg_repack#314]
I'm just now getting back into pg_repack again after a few years away from it.  I am shocked at the incredible number of open issues, many of which should have been closed by the authors long time ago. 

So I figure the authors are bogged down big time with work and could probably use some help in this regard.  I volunteer to help resolve the low hanging fruit issues by closing them with comments.  For instance I just commented on an open issue in which one of the maintainers asked the issue creator a question back in 2015 and the person never responded!  Thats how the thread ended, with the maintainer waiting for a response.  I would close that with comments to that effect. 

Do you want to take me up on my volunteer offer?  I want to make pg_repack succeed and continue to succeed.  But complaints are surfacing regarding folks losing confidence in this project because of the many open bugs.  And since most of them will probably not read many of them to discover that many should simply have been closed due to lack of response from the issue creators, they will be left with a false negative assessment.

Let me help.

**Comment by dvarrazzo** [comment]
You are welcome to help, thank you very much.

I am personally busy with other project, some free software (psycopg) and some private and paying my bills. I am disappointed that big postgres businesses have contributed nothing to this project, which seems relevant to their customers according to how much they scream for new releases whenever there is a new postgres release.

I have maintained the project as long as I had an employer interested in its maintenance. In this moment I don't have resources to give for free to EDB et al.

**Comment by dvarrazzo** [comment]
@MichaelDBA I gave you triage permission to the repos. I'm not totally knowledgeable of the available permission levels, so let's start from here and let's see if we need more.

Thank you for your help.

**Comment by MichaelDBA** [comment]
Well the only thing I have tried and tried successfully is closing those tickets that needed to be closed.  I did 3 of them today. I don't plan to do ANYTHING ELSE without consent upfront first.
  
  
   
  
  
   Here are the details of what I did so far.  Please review to see if you think I am helping and not hurting.
  
  
   
  
  
   
    Closed issue https://github.com/reorg/pg_repack/issues/26 
    Closing this issue since it was merged.
   
   
    
   
   
    Closed issue https://github.com/reorg/pg_repack/issues/50 
    Closing this issue since no response from @pfote for quite a few years! Also, partitioning has come a long way since 2015 when PG 9.5 was the current version and declarative partitioning was still years away from being a reality.
   
   
    
   
   
    Closed issue https://github.com/reorg/pg_repack/issues/53
    Closing this issue since the recompiling issue is on old distro (Ubuntu 12.04) and a very old EOLed PG Version (9.3).

**Comment by dvarrazzo** [comment]
Thank you, @MichaelDBA. Closing those tickets seems pretty uncontroversial.

If there are more you think can be close (I believe there are), feel free to do it. If someone thinks it wasn't the case we can still reopen it.

We can set up labels to classify the tickets if it helps. Feel free to propose a triaging flow if you are inclined to use one.
