### ISSUE TITLE
Public site not showing latest docs

### ISSUE THREAD

**Issue by Indigenuity** [reorg/pg_repack#320]
The docs in the file [here](https://github.com/reorg/pg_repack/blob/master/doc/pg_repack.rst) have not been deployed to the public site at https://reorg.github.io/pg_repack/.  It looks like changes haven't been deployed for over a year, at least since before 1.4.7.  

I was about to give up on the extension, thinking that it doesn't support the latest postgres.  [I'm not the only confused person](https://github.com/reorg/pg_repack/issues/276#issuecomment-1117739247)

Thanks for the work on the project!  Just wanted to make sure the maintainers knew that the docs weren't getting updated.

EDIT
What stood out to make me notice are these 2 lines, which are out of date
> PostgreSQL versions
> PostgreSQL 9.4, 9.5, 9.6, 10, 11, 12, 13

**Comment by dvarrazzo** [comment]
fixed
