### ISSUE TITLE
Latest version errors not finding index

### ISSUE THREAD

**Issue by assertnotnull** [reorg/pg_repack#325]
I have an error running the command as such:
![command](https://user-images.githubusercontent.com/821567/200054549-c53ddd4c-ef64-4a50-bffd-f2440ae78548.jpg)

Here's an output of the SQL of the table in pgAdmin
![image](https://user-images.githubusercontent.com/821567/200054159-e61a2087-6ce2-4243-803b-132c6a209ba8.png)

And the SQL of the index:
![image](https://user-images.githubusercontent.com/821567/200054303-8a276c8c-0546-43c3-8b3a-96fcf8cdc9bd.png)

I've also tried a dry run on the table but it's not finding it 
![command2](https://user-images.githubusercontent.com/821567/200054968-df1f9cc4-8c1d-4722-a640-5cc4de116602.jpg)

Am I doing it wrong?

**Comment by Melkij** [comment]
Text please, not images.

If for some reason you want to use quoted identifiers - they will always complicate your work. Like other postgresql tools (try `pg_dump -t Foo` for example), you need double quote such a identifiers. One pair of quotes will eat bash itself, another pair is required for quoted identifier.
```
$ pg_repack postgres -t "Foo"
ERROR: pg_repack failed with error: ERROR:  relation "Foo" does not exist
$ pg_repack postgres -t '"Foo"'
INFO: repacking table "public."Foo""
```

**Comment by dvarrazzo** [comment]
Thank you, @Melkij.
