### ISSUE TITLE
pass case sensitive table name with double quotes

### ISSUE THREAD

**Issue by maveriCkharsha** [reorg/pg_repack#331]
How do I pass the table name which is case sensitive. It says table name doesn't exist tried `"""public.HealthCredits""", public."HealthCredits", `

`PGPASSWORD='xxxx' pg_repack -e -h xxxxx -U xxxx -p 5432 -k AllTables -t public.HealthCredits`

**Comment by Melkij** [comment]
Like other postgresql tools (try `pg_dump -t HealthCredits` for example), you need double quote such a identifiers. One pair of quotes will eat bash itself, another pair is required for quoted identifier.

try this:
```
-t 'public."HealthCredits"'
```

**Comment by maveriCkharsha** [comment]
Thanks for the quick response. I was able to do like this too  `public.""\"HealthCredits"\""` But your answer looks clean.
