### ISSUE TITLE
We removed row in table pg_extensions 

### ISSUE THREAD

**Issue by iCheater** [reorg/pg_repack#332]
Hi! 
I have unusual situation and need some expert opinion or advice on a strategy for the next steps. 

Foreword
- He have single proccess of postgres with o lot of bases. 
- About a week ago we've faced with a memory leak on Postgres 9.5 after removing users from some bases.
- We started prepairing for separating bases, faced with troubles and we have created one more trouble. 

Chronology:
Firslty, we created the dump of DB on test server with PG10
```
pg_dump \
--jobs=1 \
--format=plain  \
--username='USERNAME' \
--exclude-table='LOGS1' \
--exclude-table='LOGS2' \
--verbose \
--dbname='DB_NAME \
--host='HOST' \
--file='DB_NAME-prod-26-01.dump'
```
Then, while we were restoring the dump, there were 2 errors:
`ERROR: could not open extension control file "/usr/share/postgresql/10/extension/pg_repack.control": No such file or directory`
`ERROR: extension "pg_repack" does not exist`

I've asked a person who were supporting PG and he told that a lot of years ago maybe he used to use it.

We started to invesigate:
 \dx showed that only 1 extension is used in the database
```
postgres=# \dx
                  List of installed extensions
   name | version | schema | Description
---------+---------+------------+----------------- -------------
  plpgsql | 1.0 | pg_catalog | PL/pgSQL procedural language
```
It was making no sense, because we able to look in `"pg_catalog"-> tables->"pg_extensions" `
 pg_repack was presented, as well as other 4 extensions
 
![pg_extensions](https://user-images.githubusercontent.com/13772028/216589142-54369fdd-bc7f-442e-99b2-6d5290e0c386.jpeg)

We've tried to remove the extension with ` DROP EXTENSION pg_repack` , but it was "not found"

Then we made a "manoeuvre"(bad experiment), deleted the row with `pg_repack ` in the table `pg_extensions ` with the idea that, we would simply restore this line here again, if something will happen. Later it turned out that it was impossible to restore.

Now when we are trying to dump there is warning "could not find referenced extension 1138714005"
```
pg_dump: last built-in OID is 16383
pg_dump: reading extensions
pg_dump: identifying extension members
could not find referenced extension 1138714005
could not find referenced extension 1138714005
could not find referenced extension 1138714005
could not find referenced extension 1138714005
could not find referenced extension 1138714005
could not find referenced extension 1138714005
could not find referenced extension 1138714005
could not find referenced extension 1138714005
could not find referenced extension 1138714005
could not find referenced extension 1138714005
could not find referenced extension 1138714005
could not find referenced extension 1138714005
could not find referenced extension 1138714005
could not find referenced extension 1138714005
could not find referenced extension 1138714005
could not find referenced extension 1138714005
could not find referenced extension 1138714005
could not find referenced extension 1138714005
could not find referenced extension 1138714005
could not find referenced extension 1138714005
could not find referenced extension 1138714005
could not find referenced extension 1138714005
could not find referenced extension 1138714005
could not find referenced extension 1138714005
could not find referenced extension 1138714005
could not find referenced extension 1138714005
could not find referenced extension 1138714005
pg_dump: reading schemas
pg_dump: reading user-defined tables
pg_dump: reading user-defined functions
pg_dump: reading user-defined types
pg_dump: reading procedural languages
pg_dump: reading user-defined aggregate functions
```
We made bad desison and now asking for some help. 

- What do you recommend to do?
- Should we try to reinstall the pg_repack extension? Is there any risk? 

PS we've reconfigured postgres config and now we have fixed memory leak

**Comment by xzilla** [comment]
You're running an unsupported database version in which you have modified the system catalogs while trying to upgrade to a different unsupported database version... ISTM the only "recommended" action would be to do some form of dump/restore (or maybe logical replication) to upgrade from 9.5 -> something supported / current, like v15 for instance. All other suggestions would be speculation / random troubleshooting.

**Comment by andreasscherbaum** [comment]
See explanation from xzilla.
