### ISSUE TITLE
Releases with precompiled binaries

### ISSUE THREAD

**Issue by mareksuscak** [reorg/pg_repack#335]
I wasn't sure where to ask so I'm submitting an issue (feel free to close if irrelevant). Would there be an interest in automating the release process more and publishing releases here on GitHub along with precompiled binaries so people don't have to download and compile the client every time? In the same vein, would there be interest in us creating a Homebrew formula and publishing said binaries on Homebrew (MacOS only) and potentially other package repositories to make installation more seamless across the supported platforms? I'd be happy to contribute some of the changes.

**Comment by andreasscherbaum** [comment]
> would there be interest in us creating a Homebrew formula and publishing said binaries on Homebrew
Do you have experiences with the process of doing this?

**Comment by za-arthur** [comment]
Because an answer wasn't provided I'm closing the ticket.
@mareksuscak feel free to re-open it.

**Comment by vmercierfr** [comment]
If it may help, there is an initiative that releases `pg_repack` as docker image at https://github.com/hartmut-co-uk/pg-repack-docker

**Comment by mareksuscak** [comment]
> Do you have experiences with the process of doing this?

Sorry folks, I completely forgot about this thread. I have never done it before but when I have time, I'll see if I can whip something up.
