### ISSUE TITLE
pg_repack  error:column "relhasoids" does not exist

### ISSUE THREAD

**Issue by docker123docker** [reorg/pg_repack#355]
windows server 2012   pg12.2 instal pg_repack1.4.8 error
![1](https://github.com/reorg/pg_repack/assets/74442348/20d76031-80af-4115-b5f7-171eab6ab1d2)

**Comment by docker123docker** [comment]
pg 12.2  pg_repack 1.4.5  error
![2](https://github.com/reorg/pg_repack/assets/74442348/bc48a7a0-62eb-41b7-b0b5-513828b4e718)

**Comment by andreasscherbaum** [comment]
@docker123docker Can you please copy the actual error message into the description? It's hard to work with blurry screenshots.

**Comment by Melkij** [comment]
@andreasscherbaum , do we support compiling on windows at all? The thought came to me that `sed` simply does not exist there and Makefile creates files incorrectly.

**Comment by andreasscherbaum** [comment]
I have no idea about Windows, and the Workflow only tests Linux.

**Comment by za-arthur** [comment]
Because more information regarding the ticket wasn't provided I'm closing it.
@docker123docker feel free to re-open it once you have more details.
