### ISSUE TITLE
Rebuilding indexes only on Postgres 9.1

### ISSUE THREAD

**Issue by andres101** [reorg/pg_repack#37]
I rebuild the indexes of a table using the following command:
pg_repack -x -t tablename dbname

I received the following error:
ERROR: query failed: ERROR:  syntax error at or near "CONCURRENTLY"
LINE 1: DROP INDEX CONCURRENTLY "public"."index_278012770"

The CONCURRENTLY keyword for the DROP INDEX statement was only introduced in PostgreSQL 9.2.
http://www.postgresql.org/docs/9.1/static/sql-dropindex.html
http://www.postgresql.org/docs/9.2/static/sql-dropindex.html

**Comment by schmiddy** [comment]
Any chance you are using a pg_repack client built against a different version of Postgres, and how did you install pg_repack? I can't reproduce your problem on a local 9.1 install with a clean build, and it looks like the only place we do DROP INDEX or DROP INDEX CONCURRENTLY is here in bin/pg_repack.c, with a seemingly correct version number check:

```C
#if PG_VERSION_NUM < 90200
        appendStringInfoString(&sql, "DROP INDEX ");
#else
        appendStringInfoString(&sql, "DROP INDEX CONCURRENTLY ");
#endif
```

**Comment by andres101** [comment]
We have 9.1 and 9.3 running on the same server. I had some trouble installing pg_repack on the 9.1 instance. I kept on getting the following error:
/usr/lib/libpgport.a(wait_error.o): In function `wait_result_to_str':
(.text+0x110): undefined reference to `pstrdup'

I found a post somewhere that mentioned adding "-lpgcommon" after "-lpgport", which worked.
