### ISSUE TITLE
pg_repack without primary/unique index

### ISSUE THREAD

**Issue by jimis** [reorg/pg_repack#370]
I have a huge 20G-row, 2TB in size, table, where I deleted the primary key on purpose since it was almost 0.5 TB in size, too big to fit in RAM, so it was slowing down queries while being unused.

Another non-unique integer column on the table is the one typically being used as a filter in all queries. That column has a BRIN index. My goal is to maintain the BRIN index, i.e. re-order the table according to this column once a month or whenever the _correlation_ metric drops below 1. I tried to use `pg_repack --order-by` for that.

### I noticed that pg_repack requires a unique index on the table.
Is there any way to alleviate this? Is it a theoretical limitation or an implementation shortcoming? 

I don't know the algorithm pg_repack uses to reorder the table so any help would be appreciated.
Thanks in advance.

**Comment by dvarrazzo** [comment]
It is a requirement, because it is necessary to identify a record uniquely in order to track concurrent modifications during repack.
