### ISSUE TITLE
Respect table order list passed as argument

### ISSUE THREAD

**Issue by benoittgt** [reorg/pg_repack#379]
Hello

I ran pg_repack with 5 tables but notices it does not respect passed table argument order

```sh
appuser@debug-benoit:/$ time pg_repack -U admin -h x.x.x -d db_name -t business_events -t platform_events -t envelopes -t off_peak_retries -t files
Password:
INFO: repacking table "public.business_events"
INFO: repacking table "public.envelopes"
INFO: repacking table "public.files"
INFO: repacking table "public.off_peak_retries"
INFO: repacking table "public.platform_events"
```

I think it should respect order because in my case I choose from the smaller table to the bigger table.

**Comment by dvarrazzo** [comment]
You can call repack 5 times if you want the order to be enforced. I don't think that the order of repacking should be part of the interface.
