### ISSUE TITLE
Version in control file in HEAD

### ISSUE THREAD

**Issue by amitlan** [reorg/pg_repack#38]
pg_repack HEAD built against PostgreSQL HEAD. Trying to CREATE EXTENSION - I get an error:

ERROR:  could not stat file "$INSTALLDIR/share/extension/pg_repack--1.3-dev0.sql": No such file or directory

install command is:

/usr/bin/install -c -m 644  pg_repack--1.3.1.sql pg_repack.control '$INSTALLDIR/share/extension/'

Missing Makefile magic? Or am I missing some instruction?

**Comment by dvarrazzo** [comment]
Try again a

    make clear
    make
    sudo make install

the installed file comes from a previous HEAD. You may also be installing the extension in a cluster and then running CREATE EXTENSION in the wrong cluster.

Anyway, I've just tested and HEAD is working ok. `1.3-dev0` is nowhere to be found in the current source.
