### ISSUE TITLE
pg_repack 1.5.0 signed integer in name of log table lead to errors 

### ISSUE THREAD

**Issue by MaximBoguk** [reorg/pg_repack#380]
Hi, oid in the database is unsigned integer however when pg_repack create log table it uses singed integer in name generation...
which lead to error during trigger call:

`
**** [local] [vxid:31/223516791 txid:976590312] [INSERT] ERROR:  syntax error at or near "-" at character 24
**** [local] [vxid:31/223516791 txid:976590312] [INSERT] QUERY:  INSERT INTO repack.log_-562678739(pk, row) VALUES(CASE WHEN $1 IS NULL THEN NULL ELSE (ROW($1.event_id)::repack.pk_-562678739) END, $2)
**** [local] [vxid:31/223516791 txid:976590312] [INSERT] CONTEXT:  unnamed portal with parameters: ....
**** [local] [vxid:31/223516791 txid:976590312] [INSERT] STATEMENT:  insert into person_history (data, event_time, event_type, initiator_id, initiator_type, person_id) values ($1, $2, $3, $4, $5, $6)
	RETURNING *
`

See funny name of the log table: repack.log_-562678739

**Comment by Melkij** [comment]
Hello
Should be fixed by #375 But this fix was committed after the release of 1.5.0

**Comment by andreasscherbaum** [comment]
@MaximBoguk Any chance you can test #375 in your environment, and confirm that it fixes your problem?

**Comment by MaximBoguk** [comment]
I tested #375 within my database and it indeed fix the issue I described in the my report.

**Comment by za-arthur** [comment]
Thanks for checking. I'm closing the ticket.
