### ISSUE TITLE
No self cleaning process in pg_repack on error.

### ISSUE THREAD

**Issue by kotsachin** [reorg/pg_repack#39]
As documentation says, pg_repack throws the following error if the given database object does not exist:

```
$ pg_repack -t tbl -o col3
INFO: repacking table "tbl"
ERROR: query failed: ERROR:  column "col3" does not exist LINE 1: ...CE pg_default AS SELECT co1,col2 FROM ONLY tbl ORDER BY col3
                                                                   ^
DETAIL: query was: CREATE TABLE repack.table_212909 WITH (oids=false) TABLESPACE pg_default AS SELECT co1,col2 FROM ONLY tbl ORDER BY col3 ````
```
There remains temporal objects created by pg_repack, like repack.log_* table or so on.

```
postgres=# \d repack.
repack.log_212909_id_seq  repack.primary_keys       repack.log_212909
repack.log_212909_pkey    repack.pk_212909          repack.tables
```

 Immediately if user run pg_repack again with existing column name, it shows another error:

```
$ pg_repack -t tbl -o col2
INFO: repacking table "tbl"
WARNING: the table "tbl" already has a trigger called "z_repack_trigger"
...
```

Though the temporal objects can be removed by DROP EXTENSION, but it seems to be better to cleanup temporal objects by pg_repack itself. As it is usual that user can do typing mistake while specifying column name, there are many chances to occur this situation. 

##### How we can improve:
We can write separate cleaning function which will call to repack_drop() for cleaning temporary objects, similar to repack_cleanup().
Pushing this cleaning function on stack using pgut_atexit_push() enables pg_repack to remove temporal objects before exiting.

Thought?

**Comment by kotsachin** [comment]
Hi,

I have created patch for above issue, which will clean temporary object or error.
Kindly check patch and reply if need improvements.
Pull request is sent at [Patch for self cleaning process in pg_repack on error.](https://github.com/reorg/pg_repack/pull/41)

Thanks and Regards,
Sachin Kotwal

**Comment by schmiddy** [comment]
Closing since PR #41 has been merged.

**Comment by keithf4** [comment]
Any chance of a new stable release soon with this fix included? Been over 4 months now since 1.3.1.

**Comment by schmiddy** [comment]
Yeah, guess we're about due for another release. FYI @dvarrazzo . I might have some time this weekend to handle the release.

**Comment by schmiddy** [comment]
FYI, I finally pushed release 1.3.2 last night.
