### ISSUE TITLE
unable to install pg_repack-1.4.7 on centos and amazon linux

### ISSUE THREAD

**Issue by shabeer22vsb** [reorg/pg_repack#394]
Below are the commands 
sudo yum install gcc postgresql-devel openssl-devel postgresql-static.x86_64 readline-devel  lz4-devel -y
sudo wget https://api.pgxn.org/dist/pg_repack/1.4.7/pg_repack-1.4.7.zip 
sudo unzip pg_repack-1.4.7.zip
cd pg_repack-1.4.7
sudo make install
cd bin
./pg_repack —version
which pg_repack 

Error
pgut/pgut-fe.c: In function ‘get_username’:
pgut/pgut-fe.c:652:14: warning: implicit declaration of function ‘getpwuid’; did you mean ‘geteuid’? [-Wimplicit-function-declaration]
  652 |         pw = getpwuid(geteuid());
      |              ^~~~~~~~
      |              geteuid
pgut/pgut-fe.c:652:12: warning: assignment to ‘struct passwd *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  652 |         pw = getpwuid(geteuid());
      |            ^
pgut/pgut-fe.c:653:23: error: invalid use of undefined type ‘struct passwd’
  653 |         ret = (pw ? pw->pw_name : NULL);
      |                       ^~

**Comment by za-arthur** [comment]
> warning: implicit declaration of function ‘getpwuid’

It seems that Amazon Linux might not have `getpwuid`. You can try to use the latest release `1.5.0`. It seems usage of `getpwuid` was removed a while ago:
https://github.com/reorg/pg_repack/commit/944dbf7a49adfed7bd2ad467ae9431e8067442a4#diff-abaa7893eaa68a091174eb232d49639709baeefee506db38f4870c0fe9a620bcL652

**Comment by Melkij** [comment]
Which version of postgresql-devel did yum install? It is not surprising that 1.4.7 will not be built on postgresql-15 and newer.

**Comment by za-arthur** [comment]
Closing the issue. Feel free to re-open it if necessary.
