### ISSUE TITLE
PG17 compatibility

### ISSUE THREAD

**Issue by Deltaus** [reorg/pg_repack#404]
Hi there, Postgres 17beta1 has been released by community and the latest released tag 1.5.0 doesn't build with it. However, the unpublished v1.5.1 does work with PG17, so may I know when v1.5.1 will be officially released? Thanks

**Comment by andreasscherbaum** [comment]
@Deltaus Can you please check if that is working for you now?

**Comment by df7cb** [comment]
@andreasscherbaum 1.5.1 has not been tagged yet.

1.5.0 fails with this regression diff:
```
diff -U3 /home/myon/projects/postgresql/pg-repack/pg-repack/regress/expected/repack-check.out /home/myon/projects/postgresql/pg-repack/pg-repack/regress/results/repack-check.out
--- /home/myon/projects/postgresql/pg-repack/pg-repack/regress/expected/repack-check.out	2023-11-22 21:10:39.000000000 +0100
+++ /home/myon/projects/postgresql/pg-repack/pg-repack/regress/results/repack-check.out	2024-09-13 22:53:25.018310529 +0200
@@ -128,7 +128,7 @@
  attname | attstattarget |    attoptions     
 ---------+---------------+-------------------
  i       |             1 | 
- t       |            -1 | {n_distinct=-0.5}
+ t       |               | {n_distinct=-0.5}
 (2 rows)
 
 --
```

I can't easily tell if this is harmless. Could a new release with PG17 support be tagged?

**Comment by za-arthur** [comment]
The version `1.5.1` was released a while ago with support of Postgres 17.
