### ISSUE TITLE
ACCESS EXCLUSIVE lock blocks queries

### ISSUE THREAD

**Issue by gcbirzan-plutoflume** [reorg/pg_repack#408]
pg_repack tries to briefly acquire an `ACCESS EXCLUSIVE` lock on the table, waits for X seconds and then kills queries that block it (or exits). This, on the surface, looks safe, but is not. In the time that pg_repack waits to acquire the lock, any transaction that wants to get even an `ACCESS SHARE` lock will block, since even unacquired `ACCESS EXCLUSIVE` locks will block less restrictive locks, including `ACCESS SHARE`.

In theory, one can work around this problem by setting a very low timeout for acquiring the lock (and not killing the conflicting transactions) and just running it in a loop, but that's annoying when trying to repack whole schemas/databases, and it adds the startup delay.

I'm not sure if it's outside of what you have in mind for pg_repack, but it'd be nice if there was a way (probably not on by default) to have it set a very low lock timeout and try in a loop to acquire that lock. This way other queries would have a way to finish, and while, granted, there could be situations in which you cannot get the lock, it wouldn't break other queries.

**Comment by za-arthur** [comment]
> I'm not sure if it's outside of what you have in mind for pg_repack, but it'd be nice if there was a way (probably not on by default) to have it set a very low lock timeout and try in a loop to acquire that lock. 

If I understand your suggestion correctly, `pg_repack` already acquires exclusive lock that way:
https://github.com/reorg/pg_repack/blob/f89c26123c7b7b6cee5100ab0005ee06143a6620/bin/pg_repack.c#L1966-L1968

**Comment by gcbirzan-plutoflume** [comment]
Oh, okay. That's weird, you're right, that's why I couldn't find any issues about this, it's been in for 14 years :). Okay, I'll need to figure out exactly what happened, since we did get blocked select queries at exactly the same time, I didn't even bother checking (sorry about that) whether it's doing the right thing.

I'll close this, thank you for the response, we'll take a closer look at exactly what happened.
