### ISSUE TITLE
[question] safe to use on system tables?

### ISSUE THREAD

**Issue by paymog** [reorg/pg_repack#411]
Through a series of unfortunate events my `pg_statistics` table is now hundreds of gigabytes large. If I vacuum this table to remove the dead pages, that breaks my api because of some idiosyncrasies of my flavor of postgres and how it does replication. 

I'm looking for alternative ways to clean up these dead pages and this seems like a great tool. Is it safe to use `pg_repack` on system tables?

**Comment by Melkij** [comment]
No, pg_repack do not allow porcessing of the system catalog tables.
(here system catalog tables are excluded https://github.com/reorg/pg_repack/blob/ver_1.5.0/lib/pg_repack.sql.in#L311 )

Even being a DBA, I find it difficult to advise anything else than `vacuum (truncate on) pg_statistic;` or even `vacuum (full) pg_statistic;` (latter with downtime).
PS: maybe it is time to upgrade to a new version of postgresql instead? =) pg_statistic is not copied by pg_upgrade

**Comment by paymog** [comment]
Ah gotcha. I figured this wouldn't be supported but thought I would ask anyways. Upgrading postgres will be even harder for us unfortunately. I guess we'll have to do a 2am vacuum of the table sometime soon. Thanks for the help!
