### ISSUE TITLE
Repack without trigger

### ISSUE THREAD

**Issue by mgagliardo91** [reorg/pg_repack#412]
We have a unique scenario where we are looking to repack an active table that gets frequent reads, but all of its writes are controlled and infrequent. The table, due to its creation from another extension, does not support triggers but in this case we do not actually need to worry about keeping track of replay logs. Our main goal is to benefit from pg_repack's ability to copy live (with handling of locks) and then ultimately `swap` carefully to ensure that nothing is broken out from under it.

Is there any simple way to run pg_repack, ignoring the steps to create/activate the replay log trigger?

Thanks!

**Comment by andreasscherbaum** [comment]
Not really, I think.

What you can do is start a transaction, get a write lock on the table, and then INSERT-SELECT into a new table. Then rename it. All in one transaction.

**Comment by za-arthur** [comment]
You can try to redefine functions `repack.get_create_trigger()` and `repack.get_enable_trigger()`:

```
CREATE OR REPLACE FUNCTION repack.get_create_trigger(relid oid, pkid oid)
  RETURNS text AS
$$
  SELECT 'SELECT 1';
$$
LANGUAGE sql STABLE STRICT;

CREATE OR REPLACE FUNCTION repack.get_enable_trigger(relid oid)
  RETURNS text AS
$$
  SELECT 'SELECT 1';
$$                                          
LANGUAGE sql STABLE STRICT;
```

or `repack.tables` view:
https://github.com/reorg/pg_repack/blob/6a3c2820ee9986d3c85e237e72ccb9336dcd4187/lib/pg_repack.sql.in#L300-L301

It works when I do a simple test. But we don't generally test such case.

**Comment by mgagliardo91** [comment]
I was able to comment out the `create_trigger` and `enable_trigger` calls and see it work - I appreciate the quick comments. One other related question, if replay logs/trigger is not a concern for our use case, does the requirement for having a table PK/not-null column still stand? Is that requirement for the trigger or is it also used during the live copy command?

**Comment by za-arthur** [comment]
AFAIK a PK/unique index is used by DELETE/UPDATE operations during applying log:
https://github.com/reorg/pg_repack/blob/6a3c2820ee9986d3c85e237e72ccb9336dcd4187/lib/pg_repack.sql.in#L312-L313

You can try to redefine `repack.primary_keys` view or delete it from `repack.tables` view:
https://github.com/reorg/pg_repack/blob/6a3c2820ee9986d3c85e237e72ccb9336dcd4187/lib/pg_repack.sql.in#L317-L318
