### ISSUE TITLE
Dropped columns kept

### ISSUE THREAD

**Issue by rodo** [reorg/pg_repack#416]
Hi,
First of all thanks for this tool that helps a lot maintaining databases in good health :+1: 

I have a question regarding the information in the pg_attribute table in catalog, why do you keep the dropped column information in it ? From my point of vie it make sense during a process of repack to forget dropped columns for ever, but if you don't do it sure there is a good reason. I'm curious about this reason

Thanks in advance

**Comment by Melkij** [comment]
In this case, we will have to rewrite all references to this table's columns in the entire pg_catalog. Rewrite correctly and track all catalog changes in new releases. Instead of simply replacing relfilenode. Difficult and error prone, without obvious advantages.

**Comment by rodo** [comment]
So fast !
Thank you for this clear answer.
