### ISSUE TITLE
Lock contention issues with pg_repack 

### ISSUE THREAD

**Issue by Durgamahesh671** [reorg/pg_repack#429]
Hi

DEBUG: Poll returned: 1
LOG: Command finished in worker 1: CREATE UNIQUE INDEX index_3199790649 ON repack.table_5832724 USING btree (id)
DEBUG: ---- swap ----
DEBUG: query failed: ERROR:  canceling statement due to statement timeout
DETAIL: query was: LOCK TABLE offer.market IN ACCESS EXCLUSIVE MODE
DEBUG: query failed: ERROR:  canceling statement due to statement timeout
DETAIL: query was: LOCK TABLE offer.market IN ACCESS EXCLUSIVE MODE

While running pg_repack i was facing this issue as concurrent selects and updates on table being repacked 
How to reslove this issue even on peak hours of business ?

**Comment by za-arthur** [comment]
`pg_repack` holds exclusive locks for a short time in the beginning and in the end. You can get a bit more details in the documentation: https://reorg.github.io/pg_repack/#details

If a table is heavily used then `pg_repack` will fail to acquire the lock. To resolve you can try to reduce table usage when starting repacking. Alternatively you can try to increase wait timeout by the option `-T`.

**Comment by Durgamahesh671** [comment]
Hi Thank you 

Can we use unlogged table to insert the data rather than logged table?

Regards.Durga Mahesh

**Comment by za-arthur** [comment]
Data of unlogged tables aren't replicated to replicas and I assume that after repacking the table on a replica will be empty. But I'm not sure how this is going to work in general during swapping old and new tables (step 6 in [the docs](https://reorg.github.io/pg_repack/#details)).

If you don't have replicas you could try to re-define `repack.create_table()` function:
https://github.com/reorg/pg_repack/blob/6a3c2820ee9986d3c85e237e72ccb9336dcd4187/lib/pg_repack.sql.in#L62-L72
I didn't test it and there might be unexpected issues with it.

**Comment by Durgamahesh671** [comment]
Yes. In case of data loss when data is in unlogged table that is not
recoverable

Regards,
Durga Mahesh

**Comment by Durgamahesh671** [comment]
Hi 

Does autovacuum block on table being repacked while it is running ?
Pg_repack failed to acquire lock for certain amount of time based on -T (specified value) at the end of repacking on 1.4.7 even there was less application traffic hence we have cancelled the repack activiy

Does pg_repack 1.5.0 work well better than 1.4.7 even there is moderate app traffic ?

**Comment by za-arthur** [comment]
Closing the issue. Feel free to re-open it if necessary.
