### ISSUE TITLE
Ability to hook up a DDL when the new repack table is being created

### ISSUE THREAD

**Issue by marcelofern** [reorg/pg_repack#432]
Hi folks,

I wonder if there's an option in which I can hookup a DDL query during the
repacking process?

After the `repacking.table_XXXX` has been created, I'd like to add an exclusion
constraint on that table before it is swapped back with the original.

I know the exclusion constraint will be validated okay for the data that is in
that table, and my rationale is that if I am already rewriting the whole table
again, I might as well do it right and there.

This would be helpful because there is no way to create an exclusion constraint
without downtime (like there is for unique constraints and check constraints),
so the only option is to create a copy of the table with the new constraint and
swap with the old one.

Let me know if this makes sense, or if there's a better way of doing that.

Thanks,
Marcelo.

**Comment by andreasscherbaum** [comment]
> if there's an option in which I can hookup a DDL query during the repacking process

This feels like one of these requests which in theory might work fine, but extend the functionality of `pg_repack` beyond it's designated job.

Similar feature requests: #379 #236 #233 #416 #412

You can copy the framework which `pg_repack` is using, and build from it a tool which creates a new table for you, as a one-time operation.

**Comment by za-arthur** [comment]
Closing the issue. Feel free to re-open it if necessary.
