### ISSUE TITLE
Document pg_repack behavior

### ISSUE THREAD

**Issue by terrorobe** [reorg/pg_repack#45]
Hi,

while looking for a documentation of what pg_repack does internally I stumbled over http://www.depesz.com/2011/07/06/bloat-happens/

In there the @depesz writes:

> Full procedure looks like this:
> 
> * create log table for changes
> * create triggers on old table to log changes
> * create new table with copy of all data in old table
> * create all indexes on new table
> * apply all changes from log table to new table
> * switch (in system catalogs) information about table files
> * drop old table

Is this still true for pg_repack? If so, it would be great if this could be mentioned in the docs.

**Comment by dvarrazzo** [comment]
Feel free to propose documentation patches, thank you.

**Comment by terrorobe** [comment]
Here you go, I hope this is factually correct and sufficient for a start.
