### ISSUE TITLE
Cannot find -ledit during make

### ISSUE THREAD

**Issue by MKo-xx** [reorg/pg_repack#48]
During build on Ubunt12.04 I'm getting this error:

gcc -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security -I/usr/include/mit-krb5 -fPIC -pie -DLINUX_OOM_SCORE_ADJ=0 -fno-omit-frame-pointer -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g pg_repack.o pgut/pgut.o pgut/pgut-fe.o -L/usr/lib/x86_64-linux-gnu -lpq -L/usr/lib/x86_64-linux-gnu -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -L/usr/lib/mit-krb5 -L/usr/lib/x86_64-linux-gnu/mit-krb5 -L/usr/lib/x86_64-linux-gnu  -Wl,--as-needed  -lpgport -lpgcommon -lssl -lcrypto -lkrb5 -lcom_err -lgssapi_krb5 -lz -ledit -lcrypt -ldl -lm -o pg_repack
/usr/bin/ld: cannot find -ledit
collect2: ld returned 1 exit status
make[1]: *** [pg_repack] Error 1
make[1]: Leaving directory `/home/mkrtich/pg_repack-1.3.1/bin'
make: *** [all] Error 2

What library is -ledit?
BTW After linking manually by removing -ledit it works fine.

**Comment by schmiddy** [comment]
That would be libedit -- on Ubuntu you should install package libedit-dev.

**Comment by MKo-xx** [comment]
Worked. Thanks
