### ISSUE TITLE
Non-zero return codes for --help and --version

### ISSUE THREAD

**Issue by kmoppel** [reorg/pg_repack#58]
Currently those commands return 1 on successful completion. Why the non-standard return codes? Would it be possible to change them still?
Cheers, Kaarel

**Comment by bwtakacy** [comment]
This seems to be a historical reason.
The pg_reorg, pg_repack forked from this, has the same return codes.
But, I'm not sure why pg_reorg does so.

I agree to return 0 for these options.

**Comment by dvarrazzo** [comment]
I think we can change them no problem and return 0.

**Comment by bwtakacy** [comment]
I have sent PR for this as #59.

**Comment by kmoppel** [comment]
Great. Thanks for the quick fix!
