### ISSUE TITLE
doc in Japanese

### ISSUE THREAD

**Issue by bwtakacy** [reorg/pg_repack#60]
I have translated pg_repack documentation into Japanese.
This is mostly for users in Japan who currently use pg_reorg but want to move to pg_repack.

https://github.com/bwtakacy/pg_repack_doc_jp/blob/master/source/pg_repack.rst

Is it okay to send a proposal to merge this into pg_repack core?

**Comment by dvarrazzo** [comment]
Of course, thank you very much.

I think it would be also useful to publish the Japanese docs on the website too (http://reorg.github.io/pg_repack/) which is done by committing in this repository (https://github.com/reorg/reorg.github.com). A merge request should address that too.

**Comment by bwtakacy** [comment]
I'm so happy to hear that :) 

I will create a pull request for repack repo and website repo.

**Comment by schmiddy** [comment]
I believe this is done in PR #61.
