### ISSUE TITLE
Please, help to build pg_repack on Gentoo

### ISSUE THREAD

**Issue by karlsoon** [reorg/pg_repack#62]
Hi!
I have installed Postgres 9.4.5 and 9.5.0.
pg_repack from master is failed to build with this error:
/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lpgcommon
/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lpgport
What info i need to provide to help you debug this problem?

**Comment by schmiddy** [comment]
It's been a while since I've used Gentoo, sorry if I'm a bit rusty :-)

In Debian-land, users generally have to install a package like [libpq-dev](https://packages.debian.org/sid/libpq-dev) which would provide the symbols you are apparently missing, from the [libpq library](http://www.postgresql.org/docs/current/static/libpq.html) which `pg_repack` needs to use. I would think Gentoo should provide this library somewhere... looking at [Gentoo's docs](https://wiki.gentoo.org/wiki/PostgreSQL/QuickStart#Installation) it sounds like they nowadays try to provide everything in a big dev-db/postgresql package. Do you have that dev-db/postgresql package, or something else? 

And could you post the rest of your build output, along with the output of running `pg_config`?

**Comment by karlsoon** [comment]
make[1]: Entering directory '/root/pg_reorg/pg_repack/bin'
x86_64-pc-linux-gnu-gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -pipe -march=core-avx2 -mavx -mavx2 -maes -I/usr/include/postgresql-9.5 -DREPACK_VERSION=1.3.2 -I. -I./ -I/usr/include/postgresql-9.5/server -I/usr/include/postgresql-9.5/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o pg_repack.o pg_repack.c
x86_64-pc-linux-gnu-gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -pipe -march=core-avx2 -mavx -mavx2 -maes -I/usr/include/postgresql-9.5 -DREPACK_VERSION=1.3.2 -I. -I./ -I/usr/include/postgresql-9.5/server -I/usr/include/postgresql-9.5/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o pgut/pgut.o pgut/pgut.c
x86_64-pc-linux-gnu-gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -pipe -march=core-avx2 -mavx -mavx2 -maes -I/usr/include/postgresql-9.5 -DREPACK_VERSION=1.3.2 -I. -I./ -I/usr/include/postgresql-9.5/server -I/usr/include/postgresql-9.5/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o pgut/pgut-fe.o pgut/pgut-fe.c
x86_64-pc-linux-gnu-gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -pipe -march=core-avx2 -mavx -mavx2 -maes pg_repack.o pgut/pgut.o pgut/pgut-fe.o -L/usr/lib64/postgresql-9.5/lib64 -lpq -L/usr/lib64/postgresql-9.5/lib64 -Wl,-O1 -Wl,--as-needed  -Wl,--as-needed -Wl,-rpath,'/usr/lib64/postgresql-9.5/lib64',--enable-new-dtags -Wl,-O1 -Wl,--as-needed -lpgcommon -lpgport -lssl -lcrypto -lz -lreadline -lrt -lcrypt -ldl -lm -o pg_repack
/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lpgcommon
/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lpgport
collect2: error: ld returned 1 exit status
/usr/lib64/postgresql-9.5/lib64/pgxs/src/makefiles/pgxs.mk:296: recipe for target 'pg_repack' failed
make[1]: *** [pg_repack] Error 1
make[1]: Leaving directory '/root/pg_reorg/pg_repack/bin'
Makefile:34: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by karlsoon** [comment]
BINDIR = /usr/lib64/postgresql-9.5/bin
DOCDIR = /usr/share/doc/postgresql-9.5.0
HTMLDIR = /usr/share/doc/postgresql-9.5.0
INCLUDEDIR = /usr/include/postgresql-9.5
PKGINCLUDEDIR = /usr/include/postgresql-9.5
INCLUDEDIR-SERVER = /usr/include/postgresql-9.5/server
LIBDIR = /usr/lib64/postgresql-9.5/lib64
PKGLIBDIR = /usr/lib64/postgresql-9.5/lib64
LOCALEDIR = /usr/lib64/postgresql-9.5/share/locale
MANDIR = /usr/share/postgresql-9.5/man
SHAREDIR = /usr/share/postgresql-9.5
SYSCONFDIR = /etc/postgresql-9.5
PGXS = /usr/lib64/postgresql-9.5/lib64/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--prefix=/usr' '--build=x86_64-pc-linux-gnu' '--host=x86_64-pc-linux-gnu' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--datadir=/usr/share' '--sysconfdir=/etc' '--localstatedir=/var/lib' '--libdir=/usr/lib64/postgresql-9.5/lib64' '--prefix=/usr/lib64/postgresql-9.5' '--datadir=/usr/share/postgresql-9.5' '--docdir=/usr/share/doc/postgresql-9.5.0' '--includedir=/usr/include/postgresql-9.5' '--mandir=/usr/share/postgresql-9.5/man' '--sysconfdir=/etc/postgresql-9.5' '--with-system-tzdata=/usr/share/zoneinfo' '--enable-integer-datetimes' '--enable-thread-safety' '--without-gssapi' '--without-ldap' '--with-pam' '--without-perl' '--without-python' '--with-readline' '--with-openssl' '--without-tcl' '--with-libxml' '--with-libxslt' '--with-zlib' '--enable-nls=en ru' 'build_alias=x86_64-pc-linux-gnu' 'host_alias=x86_64-pc-linux-gnu' 'CFLAGS=-O2 -pipe -march=core-avx2 -mavx -mavx2 -maes' 'LDFLAGS=-Wl,-O1 -Wl,--as-needed' 'LDFLAGS_EX=-Wl,-O1 -Wl,--as-needed' 'LDFLAGS_SL=-Wl,-O1 -Wl,--as-needed'
CC = x86_64-pc-linux-gnu-gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -pipe -march=core-avx2 -mavx -mavx2 -maes
CFLAGS_SL = -fpic
LDFLAGS = -L../../../src/common -Wl,-O1 -Wl,--as-needed -Wl,--as-needed -Wl,-rpath,'/usr/lib64/postgresql-9.5/lib64',--enable-new-dtags
LDFLAGS_EX = -Wl,-O1 -Wl,--as-needed
LDFLAGS_SL = -Wl,-O1 -Wl,--as-needed -Wl,-O1 -Wl,--as-needed -Wl,-O1 -Wl,--as-needed -Wl,-O1 -Wl,--as-needed -Wl,-O1 -Wl,--as-needed
LIBS = -lpgcommon -lpgport -lxslt -lxml2 -lpam -lssl -lcrypto -lz -lreadline -lrt -lcrypt -ldl -lm 
VERSION = PostgreSQL 9.5.0

**Comment by remco1976** [comment]
karlsoon, just add static-libs use flag to postgresql and re-emerge it

**Comment by dvarrazzo** [comment]
Assumed fixed
