### ISSUE TITLE
Create index with expression that uses table name

### ISSUE THREAD

**Issue by vmihailenco** [reorg/pg_repack#69]
I have following index that uses expression:

```
CREATE INDEX my_table_idx
on shard0.my_table USING gin(shard0.my_func(my_table));
```

which pg_repack rewrites as

```
CREATE INDEX index_316298 ON repack.table_17593 USING gin (shard0.my_func(my_table.*))
```

which fails with

```
ERROR: query failed: ERROR:  missing FROM-clause entry for table "my_table"
```

**Comment by amitlan** [comment]
@vmihailenco pg_repack uses `pg_get_indexdef()` system information function to get the index definitions and it returns `my_table.*` as deparsed representation of my_func()'s parameter. Now, pg_repack has no way of knowing that it should substitute `my_table.*` with `repack.table_17593.*`. Why is the function defined with `my_table` as the parameter type? Could whatever is depending on that be implemented some other way? 

Maybe someone else can chime in for some workaround...

**Comment by vmihailenco** [comment]
>Why is the function defined with my_table as parameter type?

Because I want to pass whole row to the function.

>Could whatever is depending on that be implemented some other way? 

AFAIK no, `*` does not work...

**Comment by amitlan** [comment]
How about defining the index as follows:

`CREATE INDEX name ON my_table USING gin (shard0.my_func((my_table.col1, my_table.col2, ..., my_table.colN)))`

Where `(col1, col2, ..., colN)` is equivalent to composite type `my_table`, provided they are all its columns. You don't need to write the `my_table.` prefix though. I think defining the index above way would result in something like the following as the deparsed representation:

`CREATE INDEX index_316298 ON repack.table_17593 USING gin (shard0.my_func(ROW(col1, col2, ..., colN)))`

which should work.

**Comment by vmihailenco** [comment]
As a workaround `shard0.my_func((my_table.col1, my_table.col2, ..., my_table.colN))` should work, but it is tedious to enumerate all columns. Anyway thanks for idea.

**Comment by amitlan** [comment]
Oops, totally forgot about this one:

`CREATE INDEX my_table_idx ON my_table USING gin (shard0.my_func(ROW(my_table.*)))`

**Comment by vmihailenco** [comment]
How that is supposed to fix original issue? :) There is table reference in expression (`my_table.*`).

**Comment by amitlan** [comment]
It's the surrounding `ROW()` that will make all the difference.

I think why that would work is because `ROW(my_table.*)` in the index definition is transformed differently than just `my_table` or `my_table.*` when it's stored into system catalog. That becomes apparent when it's eventually deparsed (by pg_get_indexdef()), which in the former's case gives `(ROW (col1, col2, ..., colN))`, whereas in the latter's case, we are getting `(my_table.*)`. I recommend you give it a try, :)

**Comment by vmihailenco** [comment]
Ha, following index can be repacked without any issues:

```
CREATE INDEX my_table_idx
on shard0.my_table USING gin(shard0.my_func(my_table.*));
```

@amitlan thanks for your help!
