### ISSUE TITLE
Unable to build on Amazon Linux (CentOS) - Missing lpgport/lpam

### ISSUE THREAD

**Issue by armanddp** [reorg/pg_repack#7]
Hey, 

I'm trying to build pg_repack on an Amazon Linux cluster running Postgres 9.2 but getting the following message about missing pgport/pam:

Both -devel and -contrib rpms are installed as well. 

Any help would greatly be appreciated. 

Armand

[ec2-user@ip-10-166-5-184 pg_repack-1.1.8]$ make 
make[1]: Entering directory `/home/ec2-user/src/pg_repack-1.1.8/bin'
gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard pg_repack.o pgut/pgut.o pgut/pgut-fe.o -L/usr/lib64 -lpq -L/usr/lib64 -Wl,--as-needed  -lpgport -lpam -lssl -lcrypto -lkrb5 -lcom_err -lgssapi_krb5 -lz -lreadline -lcrypt -ldl -lm -o pg_repack
/usr/bin/ld: cannot find -lpgport
/usr/bin/ld: cannot find -lpam
collect2: ld returned 1 exit status
make[1]: *** [pg_repack] Error 1
make[1]: Leaving directory`/home/ec2-user/src/pg_repack-1.1.8/bin'
make: **\* [all] Error 2

[ec2-user@ip-10-166-5-184 pg_repack-1.1.8]$ sudo yum list installed | grep postgres
Failed to set locale, defaulting to C
postgresql.noarch                    9.2-1.19.amzn1                @amzn-main  
postgresql-devel.noarch              9.2-1.19.amzn1                @amzn-updates
postgresql-server.noarch             9.2-1.19.amzn1                @amzn-main  
postgresql-upgrade.noarch            9.2-1.19.amzn1                @amzn-main  
postgresql9.x86_64                   9.2.4-1.35.amzn1              @amzn-updates
postgresql9-contrib.x86_64           9.2.4-1.35.amzn1              @amzn-updates
postgresql9-devel.x86_64             9.2.4-1.35.amzn1              @amzn-updates
postgresql9-libs.x86_64              9.2.4-1.35.amzn1              @amzn-updates
postgresql9-server.x86_64            9.2.4-1.35.amzn1              @amzn-updates
postgresql9-upgrade.x86_64           9.2.4-1.35.amzn1              @amzn-updates

**Comment by binshi** [comment]
The below command solved it for me.
`sudo yum install postgresql-static.x86_64`
source: https://forums.aws.amazon.com/thread.jspa?threadID=242418

**Comment by BastianM3** [comment]
For anyone else that runs into issues, here was the complete solution for me to get pg_repack downloaded and installed on Amazon Linux:

```
echo "Installing pg_repack deps"
sudo yum install \
   gcc \
   postgresql-devel \
   openssl-devel \
   postgresql-static.x86_64 \
   readline-devel -y

cd /tmp/
curl -sSL http://api.pgxn.org/dist/pg_repack/1.4.4/pg_repack-1.4.4.zip -o pg_repack.zip
unzip pg_repack.zip
cd ./pg_repack-1.4.4/

echo "Building pg_repack"
sudo make install
```

**Comment by nagaraju11** [comment]
> For anyone else that runs into issues, here was the complete solution for me to get pg_repack downloaded and installed on Amazon Linux:
> 
> ```
> echo "Installing pg_repack deps"
> sudo yum install \
>    gcc \
>    postgresql-devel \
>    openssl-devel \
>    postgresql-static.x86_64 \
>    readline-devel -y
> 
> cd /tmp/
> curl -sSL http://api.pgxn.org/dist/pg_repack/1.4.4/pg_repack-1.4.4.zip -o pg_repack.zip
> unzip pg_repack.zip
> cd ./pg_repack-1.4.4/
> 
> echo "Building pg_repack"
> sudo make install
> ```

Hi, I followed as you mentioned but throwing the same error. Below is the log, 

`# make
make[1]: Entering directory `/root/pg_repack/bin'
gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard pg_repack.o pgut/pgut.o pgut/pgut-fe.o -L/usr/lib64 -lpq -L/usr/lib64/pgsql -L/usr/lib64 -Wl,-z,relro   -Wl,--as-needed  -lpgport -lssl -lcrypto -lkrb5 -lcom_err -lz -lreadline -lcrypt -ldl -lm -o pg_repack
/bin/ld: cannot find -lpgport
collect2: error: ld returned 1 exit status
make[1]: *** [pg_repack] Error 1
make[1]: Leaving directory `/root/pg_repack/bin'
make: *** [all] Error 2
`

**Comment by MichaelDBA** [comment]
Solutions provided for old versions of AWS distro, PG, and pg_repack.  Closing this since old AWS distro version not available anymore
