### ISSUE TITLE
Missing pg_repack.control

### ISSUE THREAD

**Issue by Ronan-O-Keeffe** [reorg/pg_repack#77]
Hi, 

RHEL 6.7 
Postgres 9.2.15
pg_repack 1.3.3

`which pg_repack
/usr/bin/pg_repack
/usr/bin/pg_repack --version
pg_repack 1.3.3`

So it's installed and works, however when I try to create the extension in the DB: 

`CREATE EXTENSION pg_repack;`
which gives 
`ERROR:  could not open extension control file "/usr/pgsql-9.2/share/extension/pg_repack.control": No such file or directory`

`find / -name pg_repack.control`
Nothing
`locate pg_repack.control
~/pg_repack-1.3.3/lib/pg_repack.control.in
~/pg_repack-1.3.3/lib/pg_repack.control`

So the file exists in the unzipped folder from the download but doesn't exist in /usr/pgsql-9.2/share/extension/
I've tried manually copying it in but get 
`ERROR:  could not stat file "/usr/pgsql-9.2/share/extension/pg_repack--REPACK_VERSION.sql": No such file or directory`
when I try to create the extension. 

Any help appreciated, cheers! 
R.

**Comment by schmiddy** [comment]
Hm, how did you install pg_repack, and do you happen to have the installation log left? Also, what does running `pg_config` tell you (specifically `SHAREDIR` from there is important, I believe)?

**Comment by Ronan-O-Keeffe** [comment]
Hi Schmiddy, 

Cheers for the reply. 
Install: 
`wget http://api.pgxn.org/dist/pg_repack/1.3.3/pg_repack-1.3.3.zip
unzip pg_repack-1.3.3.zip
cd pg_repack-1.3.3
make
make install'. 

I had initial problems with libpgport missing, so to fix: 
`ln -s /usr/pgsql-9.2/lib/libpgport.a /lib64/libpgport.a`
Then issues with libreadline missing, so to fix: 
`yum install readline-devel.x86_64`

No install log left I am afraid. I might be able to dig out the output from my buffer later. 

Output of `pg_config`: 
`BINDIR = /usr/bin
DOCDIR = /usr/share/doc/pgsql
HTMLDIR = /usr/share/doc/pgsql
INCLUDEDIR = /usr/include
PKGINCLUDEDIR = /usr/include/pgsql
INCLUDEDIR-SERVER = /usr/include/pgsql/server
LIBDIR = /usr/lib64
PKGLIBDIR = /usr/lib64/pgsql
LOCALEDIR = /usr/share/locale
MANDIR = /usr/share/man
SHAREDIR = /usr/share/pgsql
SYSCONFDIR = /etc/sysconfig/pgsql
PGXS = /usr/lib64/pgsql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--target=x86_64-redhat-linux-gnu' '--program-prefix=' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--disable-rpath' '--with-perl' '--with-tcl' '--with-tclconfig=/usr/lib64' '--with-python' '--with-ldap' '--with-openssl' '--with-pam' '--with-krb5' '--with-gssapi' '--with-ossp-uuid' '--with-libxml' '--with-libxslt' '--enable-nls' '--enable-dtrace' '--enable-thread-safety' '--with-system-tzdata=/usr/share/zoneinfo' '--sysconfdir=/etc/sysconfig/pgsql' '--datadir=/usr/share/pgsql' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'target_alias=x86_64-redhat-linux-gnu' 'CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -DLINUX_OOM_ADJ=0'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2
CFLAGS = -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -DLINUX_OOM_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -fno-strict-aliasing -fwrapv
CFLAGS_SL = -fpic
LDFLAGS = -Wl,--as-needed
LDFLAGS_SL =
LIBS = -lpgport -lxslt -lxml2 -lpam -lssl -lcrypto -lgssapi_krb5 -lz -lreadline -lcrypt -ldl -lm
VERSION = PostgreSQL 8.4.20`

Curious about the version being reported as 8.4.20 (client not server perhaps?)
Output when I log in to Postgres
`select version();
 PostgreSQL 9.2.15 on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16), 64-bit`

**Comment by schmiddy** [comment]
Yes, it looks like you have at least part of an old Postgres 8.4.20 install hanging around, and I bet your pg_repack.control and other files got installed into /usr/share/pgsql/. You could try either getting rid of that old PG install and reinstalling `pg_repack`. The other option is to reinstall, this time telling `pg_repack` to only pick up your 9.2 install: first, find the 9.2 version of `pg_config`, I guess it should be somewhere like `/usr/pgsql-9.2/bin/pg_config`, and then you may need to set a few environment variables:
```
PG_CONFIG=/usr/pgsql-9.2/bin/pg_config make install

# or if that doesn't work, possibly you may need to set a few more environment variables,
# check these directories, but try something like this:
PATH="/usr/pgsql-9.2/bin/:${PATH}" LD_LIBRARY_PATH="/usr/pgsql-9.2/lib/:${PATH}" PG_CONFIG="/usr/pgsql-9.2/bin/pg_config" make install
```

**Comment by Ronan-O-Keeffe** [comment]
Thanks Schmiddy, 

I'll dig in tomorrow. I really appreciate the time you've taken. 
R.
