### ISSUE TITLE
Cannot build pg_repack on CentOS 7 Postgres 9.5

### ISSUE THREAD

**Issue by andrydl** [reorg/pg_repack#78]
Cannot build pg_repack on CentOS 7 Postgres 9.5  I try to run make install, and I get this :
make[1]: Entering directory `/root/pg_repack/bin'
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_ADJ=0 pg_repack.o pgut/pgut.o pgut/pgut-fe.o -L/usr/pgsql-9.5/lib -lpq -L/usr/pgsql-9.5/lib -Wl,--as-needed  -L/usr/lib64 -Wl,--as-needed -Wl,-rpath,'/usr/pgsql-9.5/lib',--enable-new-dtags  -lpgcommon -lpgport -lselinux -lssl -lcrypto -lgssapi_krb5 -lz -lreadline -lrt -lcrypt -ldl -lm -o pg_repack
/bin/ld: cannot find -lselinux
/bin/ld: cannot find -lssl
/bin/ld: cannot find -lcrypto
/bin/ld: cannot find -lgssapi_krb5
/bin/ld: cannot find -lz
/bin/ld: cannot find -lreadline
collect2: error: ld returned 1 exit status
make[1]: *** [pg_repack] Error 1
make[1]: Leaving directory `/root/pg_repack/bin'
make: *** [install] Error 2
I don't use selinux , ssl is off (in postgresql.conf). What kind of packages I need to install befor build pg_repack?

**Comment by andrydl** [comment]
Not actual, it's ld  problem

**Comment by denishpatel** [comment]
@andrydl have you passed the problem? if yes, how?

**Comment by ricsipontaz** [comment]
@denishpatel you need to install the readline-devel package.

yum install readline-devel

**Comment by andrydl** [comment]
@denishpatel  This must help you  https://github.com/denishpatel http://stackoverflow.com/questions/335928/ld-cannot-find-an-existing-library

**Comment by andrydl** [comment]
@denishpatel  This must help you http://stackoverflow.com/questions/335928/ld-cannot-find-an-existing-library . ld - is looking for libselinux.so but you only have libselinux.so.1

**Comment by jbub** [comment]
On ubuntu 14.04 i had to install `libselinux1-dev`.

**Comment by BastianM3** [comment]
For anyone else that runs into issues, here was the complete solution for me to get pg_repack downloaded and installed on Amazon Linux:

```
echo "Installing pg_repack deps"
sudo yum install \
   gcc \
   postgresql-devel \
   openssl-devel \
   postgresql-static.x86_64 \
   readline-devel -y

cd /tmp/
curl -sSL http://api.pgxn.org/dist/pg_repack/1.4.4/pg_repack-1.4.4.zip -o pg_repack.zip
unzip pg_repack.zip
cd ./pg_repack-1.4.4/

echo "Building pg_repack"
sudo make install
```

**Comment by nagaraju11** [comment]
Hello, I facing below issue while make the pg_repack
```

# make
make[1]: Entering directory `/root/pg_repack/bin'
gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard pg_repack.o pgut/pgut.o pgut/pgut-fe.o -L/usr/lib64 -lpq -L/usr/lib64/pgsql -L/usr/lib64 -Wl,-z,relro   -Wl,--as-needed  -lpgport -lssl -lcrypto -lkrb5 -lcom_err -lz -lreadline -lcrypt -ldl -lm -o pg_repack
/bin/ld: cannot find -lpgport
collect2: error: ld returned 1 exit status
make[1]: *** [pg_repack] Error 1
make[1]: Leaving directory `/root/pg_repack/bin'
make: *** [all] Error 2
```
