### ISSUE TITLE
Remaining log tables in repack schema

### ISSUE THREAD

**Issue by miso-belica** [reorg/pg_repack#82]
Hi,
I used to use pg_reorg with PG 9.3. After our project migrated to PG 9.5.2 we decided to switch to pg_repack. We are using *pg_repack 1.3.3* and we discovered that there are two big tables `log_17322` and `table_17322` in our database in schema `repack`. And here are my questions.

1. Can I drop these tables to free space on our servers.
2. Why are these tables still there? Shouldn't be dropped after successful repack?
3. It's possible that something is wrong with our DB when these tables are not dropped?
4. Is somewhere the documentation about these tables? What are they for? When I can drop them? ... If not, it is possible to document it somewhere?

Thanks in advance.

**Comment by schmiddy** [comment]
Typically tables only get left behind if `pg_repack` gets killed unexpectedly (or it is still running...). As long as pg_repack is not still running, it should be safe to drop those tables, either manually, or `DROP EXTENSION pg_repack CASCADE; CREATE EXTENSION pg_repack;` should also get rid of them.

**Comment by miso-belica** [comment]
Thanks for the fast answer. Can you add it into the documentation somewhere so other users will know about this?

**Comment by amitlan** [comment]
Shouldn't ad109edb5b23f07a8f15917f23d431b54d6cdf8c have fixed the behavior whereby temporary objects get left behind when `pg_repack` is interrupted/killed?

**Comment by schmiddy** [comment]
If `pg_repack` gets killed nicely, e.g. by Ctrl-C, or otherwise is able to run its atexit handlers, then yes, it should be able to clean up its mess. Of course this handling cannot be bulletproof -- the database connection may be severed, `pg_repack` may be kill -9'ed, pg_repack's OS may crash, etc. (It's also entirely possibly the atexit handling itself may not cope well with some benign kills...)

**Comment by miso-belica** [comment]
I would like to note here also, that `DROP EXTENSION pg_repack CASCADE; CREATE EXTENSION pg_repack;` is necessary, because when I deleted the tables manually I was getting `ERROR: relation "repack.log_17322" does not exist` when inserting rows into corresponding table in public schema.

**Comment by colecrtr** [comment]
Is it okay to add `DROP EXTENSION pg_repack CASCADE; CREATE EXTENSION pg_repack;` to the beginning/end of the recurring (weekly) script that I have for my dbs?
