### ISSUE TITLE
Extension has no update path from version "1.3.2" to version "1.3.4"

### ISSUE THREAD

**Issue by bhazuka** [reorg/pg_repack#89]
When updating the extension in PostgreSQL via the normal syntax "alter extension pg_repack update;" The extension update fails with the following error.

> ERROR:  extension "pg_repack" has no update path from version "1.3.2" to version "1.3.4"

This occurred in the following environment.

OS - CentOS 6.8 (latest)
DB - PostgreSQL 9.4.8

**Comment by dvarrazzo** [comment]
Updating pg_repack is not supported, but pg_repack has no state and no db object depend on pg_repack except when it's being used.. So (as per documentation, see install section) just drop extension/create extension.
