### ISSUE TITLE
repack_apply() as a callable function

### ISSUE THREAD

**Issue by sean-** [reorg/pg_repack#9]
For one reason or another (outside of the scope of this bug report), I had to ctrl+c a pg_repack that was in progress. This left the trigger in place and the repack table growing in size (worried about duplicate keys at the time).

Anyway, I now have a repack.log_ table that has ~1M rows in it and no easy way of applying those changes back to its original table. It'd be great if there was a function that an admin could call that would apply the changes. In situations like these, I'd take a big INSERT that takes a while over something fancy that tries to conform to the APPLY_COUNT #define specified in pg_repack.c.

**Comment by dvarrazzo** [comment]
Closing this issue as nothing to do here.
