### ISSUE TITLE
Column storage setting ignored while building new table.

### ISSUE THREAD

**Issue by RaySlater** [reorg/pg_repack#94]
Hi, thanks for this extension, however I have noticed a problem with using it on tables which have a non-default storage setting for columns.

I have a table which is configured like this:

CREATE TABLE customers(
    id serial,
    name varchar(50),
    last_accessed_date timestamptz,
    data jsonb)
with (fillfactor=90);
alter table customers alter data set storage main;

The customer data is all in the "data" json field, and for performance reasons I want to avoid putting this into a toast table (the data column size is typically ~3k).

When I use pg_repack however, the new table is created with the default storage settings, and so the repacked table has all the data in the toast table. The storage settings ARE set at the end of the process however, so any new or updated data goes in the main table not the toast table.

Is there any way to set the storage options for the columns earlier in the repack process (ie when the temporary table is created, before data is copied into it)?

**Comment by RaySlater** [comment]
From debug output, it looks like it would need to change from using CREATE TABLE AS to CREATE TABLE LIKE followed by INSERT INTO SELECT.

**Comment by RaySlater** [comment]
So I tried to fix this myself without code changes by hacking the pg_repack--1.3.4.sql file.

First attempt I tried to use CREATE TABLE LIKE, and it seemed to work:
```
'CREATE TABLE repack.table_' || R.oid || '(LIKE ' || R.relname || ' INCLUDING STORAGE) WITH (' || array_to_string(array_append(R.reloptions, 'oids=' || CASE WHEN R.relhasoids THEN 'true' ELSE 'false' END), ',') || ') TABLESPACE '  AS create_table_1,

'; INSERT INTO repack.table_' || R.oid || ' SELECT ' || repack.get_columns_for_create_as(R.oid) || ' FROM ONLY ' || repack.oid2text(R.oid) AS create_table_2,
```
However it failed when it tried to repack a table which had some deleted columns.

So I had to go back to using CREATE TABLE AS, but creating the table with no data. Then modify the repack table with the correct storage options, and finally inserting the data.

```
CREATE FUNCTION repack.set_storage_options(oid)
  RETURNS text AS
$$
SELECT 'ALTER TABLE repack.table_' || $1 || array_to_string(repack.array_accum(c), ',') FROM (SELECT
        CASE attstorage
                WHEN 'p' THEN ' ALTER ' || quote_ident(attname) || ' SET STORAGE PLAIN'
                WHEN 'm' THEN ' ALTER ' || quote_ident(attname) || ' SET STORAGE MAIN'
                WHEN 'e' THEN ' ALTER ' || quote_ident(attname) || ' SET STORAGE EXTERNAL'
                WHEN 'x' THEN ' ALTER ' || quote_ident(attname) || ' SET STORAGE EXTENDED'
        END AS c
FROM pg_attribute
WHERE attrelid = $1 AND attnum > 0 AND NOT attisdropped ORDER BY attnum
) AS COL
$$
LANGUAGE sql STABLE STRICT;
```
```
' AS SELECT ' || repack.get_columns_for_create_as(R.oid) || ' FROM ONLY ' || repack.oid2text(R.oid) || ' WITH NO DATA; ' || repack.set_storage_options(R.oid) || '; INSERT INTO repack.table_' || R.oid || ' SELECT ' || repack.get_columns_for_create_as(R.oid) || ' FROM ONLY ' || repack.oid2text(R.oid) AS create_table_2,
```
This seems to work for me, but it is by no means fully tested.

**Comment by dvarrazzo** [comment]
I would like to release 1.4 with this issue fixed. I've taken an exploratory look: we may only change the storage for the attributes whose storage is different from the type default, i.e. for example:

```
# alter table foo.bar alter data set storage external ;
# select attrelid::regclass, attname, atttypid::regtype, attstorage,
    case when attstorage = 'p' then 'PLAIN'
        when attstorage = 'm' then 'MAIN'
        when attstorage = 'e' then 'EXTERNAL'
        when attstorage = 'x' then 'EXTENDED' end as new_storage
from pg_attribute a
join pg_type t on t.oid = atttypid
join pg_class r on r.oid = a.attrelid
join pg_namespace s on s.oid = r.relnamespace
where typstorage <> attstorage
and nspname <> 'pg_toast';
 attrelid | attname | atttypid | attstorage | new_storage 
----------+---------+----------+------------+-------------
 foo.bar  | data    | jsonb    | e          | EXTERNAL
(1 row)

**Comment by MasahikoSawada** [comment]
I've created PR fixing this issue. I separated `CREATE TABLE AS` into two phases, and added a new phase to change column storage before copying data after created table if required. Accordingly,
