### ISSUE TITLE
cancelling backends

### ISSUE THREAD

**Issue by MichaelDBA** [reorg/pg_repack#98]
Previously closed issues, 76 and 90, both addressed the problem with pg_repack attempting to cancel or kill other PIDs that interfere with it when the wait threshold has passed.

But I see no resolving of these issues.  Can you provide a status update for feature request to stop pg_repack from automatically attempting to cancel or terminate other PIDs?

Without this fix, we are prevented from running pg_repack in our prod environments.

Thanks in advance.

**Comment by jirihlinka** [comment]
As stated in issues @MichaelDBA  mentioned, I have the same problem.
@schmiddy: do You have any idea when this will be addressed and when You'll release a new version, please?

Thanks,
Jiri

**Comment by schmiddy** [comment]
I think it'd be fairly straightforward to implement some handling for the existing `--wait-timeout` parameter that does what you're asking for, e.g. if `wait_timeout == 0` we would skip the `pg_{cancel,terminate}_backend()` calls in `kill_ddl()` and `lock_exclusive()`. I haven't coded that up yet, a PR would be welcome.

**Comment by jirihlinka** [comment]
@schmiddy : I'd prefer separate parameter for wait-timeout and for running pg_repack without pg_{cancel,terminate}_backend() calls to separate these two functionalities, i.e. parameter --safe or something? :-)

@MichaelDBA : Your opinion?

**Comment by MichaelDBA** [comment]
Yes, I'd prefer a separate parameter for this scenario:

I'd like pg_repack to wait a certain time, but end gracefully without attempting to cancel/kill other PIDs.  So you would need 2 parms to do that I think.

**Comment by jirihlinka** [comment]
Hi @schmiddy , may I kindly ask you for some estimation for release of pg_repack's new version with this functionality?

**Comment by MasahikoSawada** [comment]
+1 to separate parameter(`--safe`, `--dont-kill-backend` or `--without-cancel`?). If we use `wait_timeout == 0` then pg_repack ends up with error immediately after failed to acquire lock at once.

Or we could change the default behavior of pg_repack. We don't cancel and terminate any other backends by default.  If timed out, we give up to repack the target table. If new option (maybe `--force`?) is set, pg_repack do cancel and terminate other conflicting backends as current pg_repack doing.

**Comment by MichaelDBA** [comment]
I am open to any of these suggestions.  Please implement asap so I can use pg_repack again in our production environment.

Thanks in advance.

**Comment by MasahikoSawada** [comment]
Created PR #108. Please review and test it.

**Comment by MichaelDBA** [comment]
Thank you, when will it be in pg repo?
